### ISSUE TITLE
unable to utilize colorpicker with reactive forms in angular 4.

### ISSUE THREAD

**Issue by monsteradurm** [zefoy/ngx-color-picker#10]
Form data isnt updating with colors selected using picker. Is it possible to use this in such a manner? looking to save data in form as string in rgba format.

**Comment by monsteradurm** [comment]
Managed to get it working using the following:

`<input [(colorPicker)]="color" [style.background]="color" [cpOutputFormat]="'rgba'" class="colorPicker" [style.background]="rgbaText" [value]="color" (colorPickerChange)="colorProfileForm.controls.navigation.controls.brand.setValue($event)">`

Thanks.

**Comment by iCodr8** [comment]
Other option...

```
      <input
        [colorPicker]="form.get('brand').value"
        [value]="form.get('brand').value"
        (colorPickerChange)="form.get('brand').setValue($event)"
        class="colorPicker"
        formControlName="brand">
```

**Comment by ekstremedia** [comment]
Thank you guys for this. Using @iCodr8's apprach works for me.

**Comment by statellite-darryl** [comment]
Another option would be to make the color binding a property which would handle the setValue and getting the value in the code.

**Comment by nico2984** [comment]
requested changes: done.
