### ISSUE TITLE
install fails

### ISSUE THREAD

**Issue by SebastianRuecker** [zefoy/ngx-color-picker#104]
hey guys,

i got with the install command `npm install ngx-color-picker --save` following error message.

> npm ERR! Unexpected token < in JSON at position 16354
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /Users/.../.npm/_logs/2018-03-06T11_51_20_196Z-debug.log

Can you help me? :-)

Regards

**Comment by sconix** [comment]
There is something wrong with you applications package.json nothing related to this library.
