### ISSUE TITLE
Error on incorrect color

### ISSUE THREAD

**Issue by HATyCEHKA** [zefoy/ngx-color-picker#105]
If I user inputs incorrect color to color-picker it breaks all application with error:
![image](https://user-images.githubusercontent.com/26141774/37098516-143c2554-222f-11e8-9c5e-69a7ef5124bb.png).

There is property cpFallbackColor. Why it is not used in this situation?

**Comment by sconix** [comment]
Could you tell how to replicate this error? I can not get error by typing a incorrect color in the color dialog.

**Comment by HATyCEHKA** [comment]
https://stackblitz.com/edit/github-9qb7kr

Enter in text edit something wrong, for example, "#ggg" and then click on square to open color picker

**Comment by sconix** [comment]
Thanks, it should use fallback color in that situation, but seems that there is a bug. I will release a new version soon.

**Comment by sconix** [comment]
I just release 5.3.4 which should fix this error. Let me know if there are still problems with the fallback color handling.
