### ISSUE TITLE
How to disable the color picker input box ?

### ISSUE THREAD

**Issue by Sathishchary** [zefoy/ngx-color-picker#106]
HI 
My requirement is to disable the color picker text box with boolean condition, I have tried with disabled input option, but its not working perfectly, is there any way to disable color picker from user do not to click on that.

tried like this.
```
html:
<style>
     .disablePlayerValues {
	  pointer-events: none;
	  opacity: 0.6;
	}
</style>
<input [(colorPicker)]="compPlayerColor" [style.background]="compPlayerColor" formControlName="playerColor" [value]="compPlayerColor"												 (colorPickerChange)="changePlayerColor($event)" 
[class.disablePlayerValues]="disablePlayerColor" [cpPosition]="'bottom'"[cpWidth]="'200px'" [cpHeight]="'265px'" />

component:
disablePlayerColor = true;
```

but its not working , can you help me to disable this color picker or is there any way to do with the plugin?

**Comment by sconix** [comment]
I added disabled input for the 5.3.5 version to make this easier.
