### ISSUE TITLE
Error: Metadata version mismatch for module

### ISSUE THREAD

**Issue by mzrokz** [zefoy/ngx-color-picker#107]
I am getting the same issue as described in #97

Package.json

```
"@angular/animations": "4.4.6",
    "@angular/common": "4.4.6",
    "@angular/compiler": "4.4.6",
    "@angular/core": "4.4.6",
    "@angular/forms": "4.4.6",
    "@angular/http": "4.4.6",
    "@angular/platform-browser": "4.4.6",
    "@angular/platform-browser-dynamic": "4.4.6",
    "@angular/router": "4.4.6",
    "@ngui/auto-complete": "^0.16.1",
    "@types/jquery": "^3.2.11",
    "ngx-color-picker": "^5.3.5"
```

ERROR in Metadata version mismatch for module /node_modules/ngx-color-picker/dist/ngx-color-picker.d.ts, found version 4, expected 3, resolving symbol AppModule in /src/app/app.module.ts, resolving symbol AppModule in /src/app/app.module.ts

**Comment by sconix** [comment]
You need to have correct version installed, read the README or at least the couple first lines.

**Comment by mzrokz** [comment]
I tried using @prev to install but still no luck.

**Comment by sconix** [comment]
Its @prev, but if you already have a version set in package.json I am not sure if npm updates the package.json correctly. You just have to verify that you have the 4.x version installed of this library and no the latest.
