### ISSUE TITLE
Extend cpToggleChange event to output color value as well as status

### ISSUE THREAD

**Issue by amihaylov** [zefoy/ngx-color-picker#108]
This would be very handy if s.o. does color calculations and or data manipulation and doesnt want for example to send request on every input/slider/picker change, but only when the dialog is closed.
Also could have new method instead of introducing breaking changes to cpToggleChange.

**Comment by sconix** [comment]
So why not just listen for the color events and check the toggle value if open then do nothing. So this is fully doable with current events, sure this would make things slightly easier so I could add this at some point or will accept PR naturally.

**Comment by amihaylov** [comment]
That's what I'm doing currently, yet I think it will be a little handier to have separate method. Will propose PR when I have free time.

**Comment by sconix** [comment]
I will soon release 5.3.8 that has colorPickerOpen and colorPickerClose events that emit the current color.

**Comment by vvolodin** [comment]
Had these events ever been added?
