### ISSUE TITLE
Input changes not reflected after moving the slider for the first time

### ISSUE THREAD

**Issue by jostschmithals** [zefoy/ngx-color-picker#109]
Hi!

First of all thank you very much for maintaining this cool and useful Angular widget!

Today I'm working for the first time with the color picker and noticed a bug which doesn't occur on the demopage, thus it might be fairly new:

After having moved the hue slider at least one time ...
- neither changed values in the input fields 
- nor clicks on the preselect buttons

... are reflected in the "saturation-lightness" area.

Steps to reproduce:

1. create a new Angular CLI project
2. inside the project run `npm install ngx-color-picker --save`
3. add FormsModule and ColorPickerModule to the imports array of AppModule
4. add to app.component.html: `<input [(colorPicker)]="color" [style.background]="color"/> `
5. add to app.component.ts: `color = '#ff0000';`
6. run `ng s`

(nothing special up to now)

7. change an input value by typing: everything okay
8. drag the hue slider (in the example below to cyan): still everything okay
9. (after moving the slider!) change an input value by typing (in the example below to yellow)

**The result: the slider and the "saturation-lightness" area don't reflect the changes:**
![colorpicker](https://user-images.githubusercontent.com/5700294/37488031-af57957c-2893-11e8-8f8b-20ad775c2502.PNG)

**The same issue can be noticed when clicking the preselect buttons (but also not until having moved the slider).**

On the demo page https://zefoy.github.io/ngx-color-picker/ it's not quite perfect (the slider doesn't reflect the change), but the "saturation-lightness" area has the correct color. From my point of view this is much better:

![colorpicker-demo](https://user-images.githubusercontent.com/5700294/37488044-b868b8d0-2893-11e8-98d3-47926e53065c.PNG)

**Comment by sconix** [comment]
It seems that the previous changes have broken something. I will release a fix tomorrow.

**Comment by jostschmithals** [comment]
I'm looking forward to it :)

**Comment by sconix** [comment]
I just released 5.3.6 it should fix this issue, let me know if it does not.

**Comment by jostschmithals** [comment]
Wow, that was fast!

At the first glance it seems to **work perfectly with both the hex input and the presets buttons** (even better than on the demo page, since the slider behaves correctly as well).

But I noticed two problems:

1.  In RGB and HSL mode the behavior is the same like before:

![blue](https://user-images.githubusercontent.com/5700294/37493755-5664eb5a-28a6-11e8-8f79-20fe6fd37ded.PNG)

2.  And at the beginning I get a white color now (this worked correctly before):

![white](https://user-images.githubusercontent.com/5700294/37493635-e1db10d4-28a5-11e8-8e0b-79d45a61bedd.PNG)

**Comment by sconix** [comment]
Forgot to add the same fix for the dialogs internal input and not just for the outside input so the number 1 is easy fix.

The fix should not have any effect on the case 2. Can you describe bit more what should be the color in case 2, i.e. what is the color set to. I have bit trouble understanding what is wrong in that case.

**Comment by jostschmithals** [comment]
Ah - sorry - my fault: I was referring to the first opening of the color picker. In this case it should show the color of the input field.
But in my ts file a had the color accidentally defined as 'red' instead of '#ff0000'. But of course this is only supported as a CSS background color in the input field itself, but not in the color picker.

**Comment by sconix** [comment]
Ah makes sense I was already wondering that in the initial post that are you using the red text as an input. I just released 5.3.7 which has the same fix applied to rgb and hsl inputs so it should work now. Of course let me know if some issues are still left.

**Comment by jostschmithals** [comment]
I can confirm that everything seem to work perfectly now. I will test this now thoroughly in my project.

Thank you very much again for the quick fix!

Related to my mistake: I've edited it in my first post from `'red'` to `'#ff0000'`, so that further readers aren't confused. The reason for my mistake: Since I'm using the color picker for WebGL, where hex numbers (e.g. `0xff0000`) are used, I've to convert these from/into the CSS-like string format (`'#ff0000'`), and I was too optimistic, that the CSS color names would also be supported by the color picker. But that's of course not the case and would not be an important feature anyways.
