### ISSUE TITLE
Color picker is not shown on top

### ISSUE THREAD

**Issue by TheSorm** [zefoy/ngx-color-picker#114]
I try to use the color picker with the ngx-chips module. The Problem is that the color picker is not rely shown on top of everything else. You can just only see a little bit of the color picker in the right corner of the box and it dose something when you click around a bit. Hope there is a simple fix for that.
```
               <tag-input [ngModel]='items' (onSelect)="onSelect($event)" theme='bootstrap' [modelAsStrings]="true" name="tags"  #input>
                <ng-template let-item="item" let-index="index" > 
                  <div [(colorPicker)]="color" [style.background]="color" [ngStyle]="{'background-color': item}">
                    <span>
                        {{ item }}
                    </span>
                    
                    <delete-icon (click)="input.removeItem(item, index)"></delete-icon>
                    </div>
                </ng-template>
            </tag-input>
```

**Comment by TheSorm** [comment]
![colorpicker](https://user-images.githubusercontent.com/38594743/39089218-e04a5908-45c1-11e8-85f2-26bd4d7e2c1d.PNG)

Left is without the color picker and right is clicked so it should show the color picker but it just show this thing on the right edge.

**Comment by sconix** [comment]
That looks like the chip element might have overflow: hidden style that clips the dialog away. So first you should try to fix the styles. If you can not then you can use the cpUseRootViewContainer (which requires you to have public viewContainerRef exposed in your root component) option to make the dialog go to the root element instead inside the element, but this method is then again vulnerable to other styles problems, but might work out of the box as well.

**Comment by TheSorm** [comment]
Thank you! I did it with changing the overflow to visible :)
