### ISSUE TITLE
Color picker popup is getting closed on selection of a color when having array of colors

### ISSUE THREAD

**Issue by anushamramyam** [zefoy/ngx-color-picker#118]
Hi,

I have a requirement like need to show list of colors [array of colors]. when click on color, color picker pop up is opening and on click of color picker pop up to choose a color, is getting close on first click only,  instead of retaining the popup. Hence we are not able to choose any other color.The color picker is behaving differently when it is single element than array of color picker

.html:
-------
 <span *ngFor="let colors of editor_chartOptions.colors; let i = index;"> 
       <input [style.background]="editor_chartOptions.colors[i] 
              [(colorPicker)]="editor_chartOptions.colors[i]" style="width:18px;"  />
</span>

.ts:
---------
public editor_chartOptions.colors = [
        "#7cb5ec",
        "#434348",
        "#90ed7d",
        "#f7a35c",
        "#8085e9",
        "#f15c80",
        "#e4d354",
        "#2b908f",
        "#f45b5b",
        "#91e8e1"]

Is there anything am I missing?
I have attached the screen shots,.

![color-picker1](https://user-images.githubusercontent.com/31650367/40343929-f83f29c0-5daf-11e8-83b6-4b67c267786e.PNG)

![color-picker2](https://user-images.githubusercontent.com/31650367/40343930-f86af17c-5daf-11e8-888f-10dda23f4f97.PNG)

**Comment by sconix** [comment]
There seems to be some bug in the service when ngFor is used. I check this today and release a fix.

**Comment by anushamramyam** [comment]
Thank you for your reply.

**Comment by sconix** [comment]
Sorry I was wrong this is not a bug. Of course the problem is that since you are using ngFor when ever the color value changes it causes change detection and angular will destroy the element and create it again. So to avoid that happening you need to use trackBy for the index in your ngFor loop so that elements wont get destroyed.

**Comment by anushamramyam** [comment]
Thank you. Working fine
