### ISSUE TITLE
White color not working when chosen

### ISSUE THREAD

**Issue by ivano33z** [zefoy/ngx-color-picker#119]
Hello, a great project thank you very much for maintaining it for free.

I m wondering if you might know why does when i select white color as first color it does not update the colors.  If i select some other color first like black for example and then white -- then white color is succesfully selected as the current color.

Do you know what might be causing this.

Steps to reproduce.

- Make white color available as preset color
- Click on color picker
- Choose white as the first color

**Comment by sconix** [comment]
It works in the example app at least for me. So does it work for you there? If yes then what is the default value you are using in your app? There might be some small bug, but I would need a way to replicate this and at least for me that works in the example app.

**Comment by ivano33z** [comment]
Hello Sconix,  thanx for quick reply.     Unfortunately or fortunately...  it doesent work on the example app either,   please go to https://zefoy.github.io/ngx-color-picker/  and try the last example.
I made a video of the problem  as i m clicking on white preset button when i hover over it. 
https://www.dropbox.com/s/r7zp3mi9rf5aksj/clip0051.avi?dl=0

**Comment by sconix** [comment]
Your welcome, version 6.3.0 is out now with one other bug fix and support for closing the dialog from esc/enter keys.
