### ISSUE TITLE
'ColorPickerModule' is not exported by node_modules/ngx-color-picker/dist/index.js

### ISSUE THREAD

**Issue by Elohina** [zefoy/ngx-color-picker#12]
Hi, I am trying to make the bundle.js using Rollup as described in the cookbook AHEAD-OF-TIME COMPILATION of angular.io. But when I configure and run the rollup-config.js I have this errors:

![image](https://cloud.githubusercontent.com/assets/8374968/26204874/298e4fbc-3bae-11e7-9602-1ed08e933901.png)

My configuration file  rollup-config.js has:

```
export default {
    entry: 'src/main.js',
    dest: 'src/build.js', // output a single application bundle
    sourceMap: false,
    format: 'iife',
    onwarn: function (warning) {
        // Skip certain warnings

        // should intercept ... but doesn't in some rollup versions
        if (warning.code === 'THIS_IS_UNDEFINED') { return; }

        // console.warn everything else
        console.warn(warning.message);
    },
    plugins: [
        nodeResolve({ jsnext: true, module: true }),
        commonjs({
            include: [
                'node_modules/rxjs/**',
                'node_modules/ng2-modal/**',
                'node_modules/ng2-table/**',
                'node_modules/ng2-select/**'
            ],
            namedExports: {
                'node_modules/ngx-color-picker/dist/lib/color-picker.module.js': ['ColorPickerModule'],
                'node_modules/ngx-color-picker/dist/lib/color-picker.service.js': ['ColorPickerService'],
            }
        }),
        uglify()
    ]
}
```

Maybe the problem is with rollup but I want to know if you have had this problem with ColorPicker in production environment and how to solve it because with the other libraries I have no problem.

Thank you for your help.

**Comment by wartab** [comment]
You will encounter this issue with lots of packages. I do not know how the packages themselves are supposed to address this issue, but on your side, replace the named exports you ahve already by this:
`"node_modules/ngx-color-picker/dist/index.js": ["ColorPickerModule"],`

**Comment by Elohina** [comment]
Thanks @wartab but I tried with this:

```
namedExports: {
                "node_modules/ngx-color-picker/dist/index.js": ["ColorPickerModule"],
            }
```

And I still receive the same error :cry:

**Comment by wartab** [comment]
That's strange, did you see my edit? I know for a fact that this works for me

**Comment by Elohina** [comment]
Oh I didn't see the Edit, now it works!! Thanks!! :+1:

**Comment by wartab** [comment]
Great :) Glad you got it working ;)

**Comment by ohabash** [comment]
My error is slightly different. Im in ng8... there is not problem in `ng serve` but there is a problem in `ng serve --prod`
> Module not found: Error: Can't resolve "ngx-color-picker.ngfactory"
