### ISSUE TITLE
issue with RTL

### ISSUE THREAD

**Issue by beesmartir** [zefoy/ngx-color-picker#121]
when application direction is rtl, color picker pointer goes out of color pallete.

**Comment by sconix** [comment]
You can fix it with styles, I will add some default styles for next release that will try to force correct styles.

**Comment by sconix** [comment]
I just tried to set rtl styles for body/html and color picker still works properly, so how are you setting rtl?

**Comment by imanfattahi** [comment]
> when application direction is rtl, color picker pointer goes out of color pallete.
I just added these lines, and everything works properly:

ngx-colors-panel {
    right: 30px;
    left: auto;
}
