### ISSUE TITLE
Changing the UI

### ISSUE THREAD

**Issue by kaisong11** [zefoy/ngx-color-picker#126]
Hi, is there anyway I can change the UI of the color picker to something like this 
![untitled](https://user-images.githubusercontent.com/40623792/41957911-0787b58c-7a1b-11e8-8df8-959ea0d95007.jpg)

**Comment by sconix** [comment]
Sure, just make some custom CSS rules to style it like you want.

**Comment by kaisong11** [comment]
thanks
