### ISSUE TITLE
Changing color of the color picker dynamiccaly

### ISSUE THREAD

**Issue by meiuqer** [zefoy/ngx-color-picker#13]
How would i change the color value of the color picker in this case:

If i change the color in the color box or hue box, and the alpha channel is at 0 in rgba mode then i want to set the alpha to 1. 
But if i wanted to change the alpha with the alpha slider it should change accordingly.

Im trying to find a solution but with only the $event value that is "rgba(255,255,255,1)" it's really hard to get  that logic going. Is there a solution for this problem that i'm overlooking? 

Thanks in advance.

**Comment by sconix** [comment]
I don't think that is possible now, but I could look into adding an event that would also tell what was changed on next week.

**Comment by meiuqer** [comment]
That could be helpful yes! Thank you

**Comment by sconix** [comment]
Soon to be released 4.0.2 has now cpInputChange and cpSliderChange outputs that tell what input/slider was changed and to what value. Hopefully this does the trick for you, if there are any problems please let me know.

**Comment by meiuqer** [comment]
Btw, this is really helpful. My messy code is way cleaner with this. Thanks!
