### ISSUE TITLE
cpDefaultInput - allow HEX as default and have RGBA optional (without HEX8 default)

### ISSUE THREAD

**Issue by stephengardner** [zefoy/ngx-color-picker#135]
Desired outcome:
Having HEX as the default, RGBA as optional, and not default to HEX8.

The fix we thought was to use Alpha channel as "always", and default to HEX, but this produces HEX8 and that has caused compatibility issues.

cpDefaultInput to "hex", with alphaChannel enabled, should allow for standard HEX input but also RGBA when toggled.

**Comment by sconix** [comment]
For 6.6.2 I enabled old 'auto' option for the cpOutputFormat. So if you now set cpOutputFormat to 'auto' and cpAlphaChannel to 'enabled' you will get either hex or rgba as output depending if there is alpha set or not. So this way you get the HEX as default input and no HEX8 output (that you would get with alphaChannel always).

**Comment by stephengardner** [comment]
Tested - works great.  Super appreciated
