### ISSUE TITLE
Possible support for limited colour options (Monochrome, Greyscale)? 

### ISSUE THREAD

**Issue by HTimms** [zefoy/ngx-color-picker#139]
Would it be possible to support different colour modes/ranges? 

We currently use the colour picker for label design, and the printers we have sometimes have different colour capabilities. Some only work in monochrome, some only work in greyscale, some only work with monochrome with the exception of red.

**Comment by sconix** [comment]
At least the moment we do not have need for this so its very unlikely that I would add this kind of feature, but PR is always welcomed.

**Comment by HTimms** [comment]
Okay, thanks for the quick response!
