### ISSUE TITLE
[bug?] When using [cpPosition] the position changes the second time you open the color picker

### ISSUE THREAD

**Issue by meiuqer** [zefoy/ngx-color-picker#14]
```
`  <div class="color" 
    [cpOutputFormat]="'rgba'" 
    [colorPicker]="color" 
    (colorPickerChange)="onChangeColor($event)" 
    [cpOKButton]="true" 
    [cpPresetColors]="['#000000', '#ff0000', '#00ff00', '#0000ff', '#ffff00']"  
    [cpPosition]="top"
    [cpPositionOffset]="offset">
</div>`
```

This is how my colorpicker is coded. The first time i open it it opens correctly. The second time it jumps down for some reason. Maybe this is a bug? Or am i doing something wrong?

**Comment by sconix** [comment]
Hard to say, I will do some testing and see how the position thing was implemented. I suspect some style problem, but can't say for sure without looking into this matter bit more deeply.

**Comment by meiuqer** [comment]
Thanks! Keep me posted!
