### ISSUE TITLE
Color is not picked in the texbox in the Edit mode

### ISSUE THREAD

**Issue by NeelBhatt** [zefoy/ngx-color-picker#141]
I am using this library with angular form group and I am using this for add and edit both.

When I add and store the hex value in the database and when I try to open the same page again, even though the correct hex are displayed on the textbox
![color](https://user-images.githubusercontent.com/10865446/46408415-b2aef180-c72f-11e8-9616-3514b006cfe2.png)
 but the textbox is not picking the background color as per the hex. Where am I doing wrong?

**Comment by sconix** [comment]
If I understand your questions correctly its about how to use Angular and not about this library. For getting general Angular help that there are better forums in Stackoverflow etc.
