### ISSUE TITLE
cpOutputFormat 'auto' - return HEX to default when opacity is 1

### ISSUE THREAD

**Issue by stephengardner** [zefoy/ngx-color-picker#142]
I love that cpOutputFormat 'auto' and cpAlphaChannel 'enabled' will output HEX and will switch to RGBA if opacity is specified.

It would be nice if, after sliding from opacity < 1 back to opacity: 1, HEX became the default again.

Currently it will show HEX, then it will switch to RGBA, and it will always stay RGBA even after opacity returns to 1.  This is a slightly obscure use case, but for our app it would be helpful.

**Comment by sconix** [comment]
I will check this after my holiday is over. This sounds like a small bug.
