### ISSUE TITLE
Zoom style issue

### ISSUE THREAD

**Issue by ycpatel813** [zefoy/ngx-color-picker#143]
Hi,

It is a very good plugin for color picker but I am facing an issue in cursor position when I am using below CSS property. I couldn't even use drag and drop color correctly. 

  html { zoom : 90% }

Please provide help on it. Thanks in advance.

**Comment by sconix** [comment]
Using zoom causes always style issues at least I am not aware of any browser where that would not be a case. So at least I am not too keen on supporting using zoom and do not even know how to do that. Naturally I will accept PR's to fix the issue if it can be fixed, but sadly I do not have time to look into this kind of issue atm.

**Comment by ycpatel813** [comment]
Hi @sconix 
Thanks for the valuable answer. We are in a shortfall of time so I couldn't make PR for zooming issue.

For my issue resolution, I have added below CSS property and everything working fine.

color-picker{
  zoom:"110%"
}

Thanks.
