### ISSUE TITLE
Build fails with enabled fullTemplateTypeCheck

### ISSUE THREAD

**Issue by maxkorz** [zefoy/ngx-color-picker#144]
Hello. I can't build app in AOT mode with the new release (7.0.0), I get the following error:
`ERROR in src\app\app.component.html(1,1): : Directive ColorPickerDirective, Expected 0 arguments, but got 1`

when I have [fullTemplateTypeCheck](https://angular.io/guide/aot-compiler#fulltemplatetypecheck) option enabled in `tsconfig.json`
```
  "angularCompilerOptions": {
    "fullTemplateTypeCheck": true
  }
```

Previous version (6.8.0) works fine.

To reproduce:
1. Clone https://github.com/maxkorz/ngx-color-picker-repro
2. `npm i`
3. `ng serve --aot`

**Comment by sconix** [comment]
That sounds bit odd. I have also enabled the fullTemplateTypeCheck in the library build options and just tried enabling it in the example app as well and I do not get the error. Both library and the app builds just fine.

**Comment by maxkorz** [comment]
@sconix The error only happens with `--aot` (or `--prod`)

**Comment by sconix** [comment]
Yes, but it seems that I added the fullTemplateTypeCheck to a wrong file :) So yes I get the error now and the reason seams to be that HostListener will now error out if the event is not used in the function :o I will release 7.1.0 to fix this problem.

**Comment by maxkorz** [comment]
Thanks!
