### ISSUE TITLE
Visibility issue in safari

### ISSUE THREAD

**Issue by harshabada** [zefoy/ngx-color-picker#145]
<img width="216" alt="screen shot 2018-11-05 at 12 09 47 pm" src="https://user-images.githubusercontent.com/36442929/47981931-c1ecda80-e0f3-11e8-9b5e-8b19c5a15d13.png">

**Comment by sconix** [comment]
If you are placing the dialog inside a div that has overflow hidden then it gets cut off naturally. If you can not fix your styles you can always use the root view container config option when the dialog is placed inside the root container and not limited by parent divs.

**Comment by harshabada** [comment]
do you have any example using root view container config option

**Comment by sconix** [comment]
No, but basically you just set cpUseRootViewContainer to true and then in your application root components constructor you need to have public viewContainerRef: ViewContainerRef.
