### ISSUE TITLE
Opening Color picker messes with flex layout

### ISSUE THREAD

**Issue by leondroidgeeks** [zefoy/ngx-color-picker#146]
I am building an Angular Application with Bootstrap and want to use your colorpicker.
But somehow every time I open the colorpicker it messes with my flex items.

The following code is wrapped in a form tag:
```
<div class="form-group row">
    <label for="color" class="col-sm-3 col-form-label">Color*</label>
    <div class="col-sm-9 d-flex flex-row justify-content-between align-items-center">
      <div (click)="selectColor(color)" *ngFor="let color of colors" class="color-picker rounded d-flex justify-content-center align-items-center" [style.background-color]="color.backgroundColor" [style.color]="color.color" [class.selected]="color.selected">{{role.shortname}}</div>
      <div class="color-picker rounded d-flex justify-content-center align-items-center bg-dark">
        <i class="fas fa-hashtag text-white"></i>
      </div>
      <i (click)="generateColors()" class="fas fa-sync-alt reload"></i>
    </div>
  </div>
```

It doesn't matter where I place the following code `<input [(colorPicker)]="colorPicker" [style.background]="colorPicker" />` As soon as I click the input and open the color picker my "colored boxes" shatter.
I also tried this at different locations in my app. Same thing. Wrapping it in a Modal doesn't work.

Is there any solution for this?

**Comment by sconix** [comment]
I would say you have some styles messing up the color picker styles. At least I can not think of anything else. The color picker dialog is position absolute so it does not have any effect on flex styles unless some style you have is changing the color picker styles.

**Comment by leondroidgeeks** [comment]
You were right, I used the css class `color-picker` for divs but this class is used by the color picker itself.
