### ISSUE TITLE
Color picker not rendering in prod-mode when using alpha channel

### ISSUE THREAD

**Issue by crazyfx1** [zefoy/ngx-color-picker#147]
Using following color-picker version 7.0.1:
`                <input
                  name="shapeColor"
                  readonly
                  [(colorPicker)]="selection.item(0).fill"
                  [cpPosition]="'left'"
                  [cpAlphaChannel]="'always'"
                  [cpOutputFormat]="'hex'" />`

In dev-mode everything is fine. When I build the application in prod mode, the color picker is not rendered anymore. Only the alpha channel is visible.
![image](https://user-images.githubusercontent.com/9930385/48249228-a25af800-e3fa-11e8-9282-63476d43d687.png)

I tried to reproduce it in the stackblitz, but I don't know how to put the stackblitz into prod-mode.

It's working fine in 6.7.0.

**Comment by sconix** [comment]
I'll have to test this. I must say that this sound bit weird since the image looks like cpColorMode is set to preset and not sure how the prod build could have an effect on that parameter.

**Comment by sconix** [comment]
I tried making production build with the example app and was not able to reproduce this.

Have you tried clearing node_modules, if there is some weird problem with getting some files from older version included in the build or something. I really don't have proper ideas that could cause that.

**Comment by sconix** [comment]
This could be actually a change detection issue. I released 7.0.2 that could potentially fix the issue for you.
