### ISSUE TITLE
Inline mode with initial value `null` cause undefined in <input>

### ISSUE THREAD

**Issue by wheeljs** [zefoy/ngx-color-picker#148]
Thanks for your working, we are using the color picker in our app.
But when I used it with 'inline' mode and set the initial value to `null`, it displayed well but I got an `undefined` in the input.

![image](https://user-images.githubusercontent.com/10950946/49125439-0f2b2900-f2fb-11e8-857a-3b5d160d8b25.png)

I wrote a stackblitz to repeat it, then I found the normal mode works well.

Stackblitz: https://stackblitz.com/edit/angular-j4kdqc?file=src%2Fapp%2Fapp.component.html

In my expectation, the color picker with inline mode should get correct display in the input, like it in normal mode.

**Comment by wheeljs** [comment]
It works well after I setting cpWidth to 231.

**Comment by sconix** [comment]
I will check this for next release. The color value should not really be set to null or undefined, I have added some fallbacks to try to handle those situations properly, but really you should preferably feed the color picker with a valid color.

Anyway this is a bug since the inline works differently than normal dialog so I will look into fixing this. As a workaround you could just feed the dialog with valid color.

**Comment by kamilchlebek** [comment]
Upgrading from `7.1.0` -> `7.1.1` caused `Cannot read property 'v' of undefined`. It's being displayed even in example applications linked in `readme`

I haven't dig very deeply into this, but it seems that first change detection cycle fails on line `slider.v` in `color-picker.component.html` then second detection cycle runs properly. Seems that `detectChanges` added in this task is executed too early.

**Comment by sconix** [comment]
I what example are you seeing this? We have not run into this error in our app and haven't noticed it in the example so far.

**Comment by kamilchlebek** [comment]
Check this link: https://zefoy.github.io/ngx-color-picker/ 

In my case after upgrading color picker, after first change detection I can see picker without applied custom configuration. Then after second change detection, picker looks like it should (same as in 7.1.0)

**Comment by sconix** [comment]
I'll add a fix for 7.2.0 that should be out tonight.
