### ISSUE TITLE
Edge/IE

### ISSUE THREAD

**Issue by doczoidberg** [zefoy/ngx-color-picker#151]
Enabling alpha values and having an alpha value==1 the color doesn't update on choosing.
When using alpha 0.99 it works.

**Comment by sconix** [comment]
That sounds rather strange, the color value calculation should not be anyway browser dependent. And I can not replicate this in IE nor in Edge. So can you be bit more specific how to replicate the issue and are you using the latest version?

**Comment by doczoidberg** [comment]
yes also with latest version, But maybe this has also to do with svg attributes I have bound to the color picker.
