### ISSUE TITLE
hsva2hsla function is not working correctly

### ISSUE THREAD

**Issue by leantorres73** [zefoy/ngx-color-picker#152]
I'm trying to use this function to convert from hsva to hsla. I've logged in the console the input and output:

Hsva input:
Hsva {h: 314, s: 87, v: 100, a: 1}

Hsla output:
Hsla {h: 314, s: -1.0235294117647058, l: -4250, a: 1}

The output is not valid, we shouldn't have negative values and bigger than 100 for 'l' property. 

Basically this is what I'm doing.
`  
console.log(hsvaColor);
    
const hslColor: Hsla = this.cpService.hsva2hsla(hsvaColor);
    
console.log(hslColor);
`

Let me know if it's an issue or if I'm missing something.

Thanks

**Comment by sconix** [comment]
Saturation needs to be between 0 and 1.
