### ISSUE TITLE
while selecting color from color picker,  a background page also scrolling

### ISSUE THREAD

**Issue by Hardikkothari94** [zefoy/ngx-color-picker#153]
Hello,
 I faced this issue in IOS mobile device.I used this plugin in ionic3 project which works on mobile or Web.While selecting a color from color picker, a  background popup is also scrolling.

Can you please provide a way to stop background scrolling while selecting a color from color picker popup.

Please check the below image.
![colorpickerissue](https://user-images.githubusercontent.com/19722860/50572311-39cd3d80-0de3-11e9-97d8-d2bfbc83584c.png)

**Comment by sconix** [comment]
I'll add event propagation stopping for next release.

**Comment by Hardikkothari94** [comment]
@sconix :Thank you so much.Can you please provide the approx time when your next release will be?
