### ISSUE TITLE
Feature Request: Close the colorpicker when clicking on the color field

### ISSUE THREAD

**Issue by Abdullah0991** [zefoy/ngx-color-picker#154]
Hi,

I need to make the color picker closed when the user clicks on the color field again, I mean, after the user chose the color instead of click outside the component.

That's it, If this request isn't  a good feature idea, please can any body tell me how to do that.

**Comment by sconix** [comment]
There wont be a direct support since its bad usability imho. Usually people click instead dragging so the first color change is hardly never the final selection.

Anyway there might be some rare valid cases where closing on color change makes sense. And its already easy to do, there are already events send on all different user interactions so just use the event that makes most sense and call close function on those events.

**Comment by Abdullah0991** [comment]
Maybe I don't make it clear, when user clicks the color field the color-picker will open (normal behavior), I want when user clicks again on the color field it close the color-picker.

[picture](https://drive.google.com/open?id=1lN3RSJJLyH2gNSlOxxqniiq_c49XIkcR)

> Anyway there might be some rare valid cases where closing on color change makes sense. And its already easy to do, there are already events send on all different user interactions so just use the event that makes most sense and call close function on those events.

How can I access the color-picker methods using angular 5, I tried what you suggest but failed.

**Comment by sconix** [comment]
Ah ok now I get it. Well this I can fix.

**Comment by Abdullah0991** [comment]
Thx @sconix , please let me know when it ready ASAP.
Regards.

**Comment by sconix** [comment]
Actually now when I think of this there is no easy way to make this generally without breaking the keyboard focus opening. So this needs to be handled in the application code. I will try to think if there is any way to implement this in this library, but for now you need to add event listener to your input to close the dialog when clicked.

**Comment by Abdullah0991** [comment]
Thanks a lot @sconix , the example help me to figure the problem, I was using ColorPickerComponent to get the reference but now I use ColorPickerDirective.

**Comment by Abdullah0991** [comment]
Hi again, would you please add a boolean variable to hold the state of the color-picker (opened/closed).

**Comment by sconix** [comment]
There is the cpToggle input and cpToggleChange output so that you can either control the open state with the input or listen on the state change from the output. So you can rather easily connect for example the cpToggleChange event to update state variable in your app.

**Comment by Abdullah0991** [comment]
Hi, sorry for late response.

The `cpToggleChange` event is working well, but I had a problem:
- First I use the `click` event of the input element to check if the color-picker is opened to close it.
- When the color-picker has the focus, the `click` event will occur first then the `cpToggleChange` event, so everything works well.
- When the focus is out of the color-picker (here is the problem), the `cpToggleChange` will occur first then the  `click` event, so when I click on the color-picker for the first time it will opened and then closed immediately. After that the focus will be on the color-picker so no problem.

Any ideas to fix this problem?

**Comment by sconix** [comment]
Easiest is most likely to tap into both focus and click event with small throttle time using rxjs for example. Or just using really small timeout etc. so that if both events are triggered you only react after both have fired.

**Comment by aartiwable** [comment]
Hello, I am facing one issue related color-picker. color-picker auto change the color value when backspace the one digit, it convert into another hex value and change the color value. I don't want the value change until user change whole value.

**Comment by sairamreddye** [comment]
I am also facing the same issue don't know why it is getting updated automatically I removed the value also and tried it's not working for me I am formcontrolname in angular to patch the value any help.
