### ISSUE TITLE
Invalid Color - cpInputChange stops firing

### ISSUE THREAD

**Issue by Parmentrout** [zefoy/ngx-color-picker#155]
On an invalid rgb/hex value, (cpInputChange) stops firing as the user types.  We want to be able to catch invalid color values and notify the user accordingly.

**Comment by Parmentrout** [comment]
I noticed that, what we're wondering though is that the user is allowed to enter invalid data and then it'll default back to a valid color.  Would it be possible to open an event is the value is invalid, or keep firing cpInputChange if it's invalid as well.  For instance:
![color picker](https://user-images.githubusercontent.com/7319813/50697615-f69be600-0fff-11e9-81fe-01a284377d85.png)

**Comment by sconix** [comment]
Ah now I see that you are talking about the cpInputChange, I somehow confused it with the color changing event. So yes I guess I do not see anything wrong making it so that the event is also sent for invalid values. I will change this for the next release.

**Comment by Parmentrout** [comment]
Awesome, thank you!

**Comment by SoumitaDatta** [comment]
This fix was very useful. Currently it is only in hex value not RGB. Can this be added to RGB fields. Thank you.

**Comment by sconix** [comment]
All the other fired the event already no matter if the color can be parsed or not. For RGB the inputs itself does not allow entering other than number between 0-255. And I do not see any reason to allow user to input invalid value.
