### ISSUE TITLE
notify on invalid RGB value

### ISSUE THREAD

**Issue by SoumitaDatta** [zefoy/ngx-color-picker#156]
On an invalid RGB value, (cpInputChange) stops firing as the user types. We want to be able to catch invalid color values and notify the user accordingly

**Comment by sconix** [comment]
RGB input does not allow inputting invalid number. The input only accepts number between 0 and 255. Only HEX does not have the browser based format since browsers do not provide such field type so thats why hex does allow user to input invalid value.

**Comment by SoumitaDatta** [comment]
![screen shot 2019-01-21 at 3 34 39 pm](https://user-images.githubusercontent.com/33674741/51502174-26821200-1d92-11e9-9201-3dfc95ccda07.png)
The input currently only allows numbers but its not restricted to 0 - 255.

**Comment by sconix** [comment]
It is restricted to 0-255. What browser are you using?

**Comment by SoumitaDatta** [comment]
Latest Chrome.

**Comment by SoumitaDatta** [comment]
I took the screenshot from the demo site
https://zefoy.github.io/ngx-color-picker/

**Comment by sconix** [comment]
Ah browsers do not provide default styles for the invalid state. I will add styles for the next release.

**Comment by SoumitaDatta** [comment]
Thanks.

**Comment by sconix** [comment]
I decided to fix it to be the same way as hex input. So in 7.4.0 version all input events have valid parameter to tell if the input from the user was valid or not.

**Comment by SoumitaDatta** [comment]
Thanks for the change.
