### ISSUE TITLE
mutliple textbox getting same color

### ISSUE THREAD

**Issue by mukeshphpdev** [zefoy/ngx-color-picker#157]
`<input [(colorPicker)]="color" [style.background]="color"/>
<input [(colorPicker)]="color" [style.background]="color"/>`

**Comment by wartab** [comment]
You might wanna check what Angular's two-way binding does: https://angular.io/guide/template-syntax#two-way-binding---

**Comment by mukeshphpdev** [comment]
can you make 2 textbox code

**Comment by mukeshphpdev** [comment]
`ERROR Error: Uncaught (in promise): Error: Cannot assign to a reference or variable!`
getting this when using another variable

**Comment by mukeshphpdev** [comment]
`<div *ngFor = "let item of keys;let i = index;" class="form-group">
                      <label><b>{{item}}</b></label>
                      <input type="text" id="{{item}}" name="{{item}}" [ngModel]=""
                      (colorPicker)="i" value="i" class="form-control">
                  </div>`

this is my latest code 
currently color picker is coming but when select any color, color code is not coming in textbox

**Comment by sconix** [comment]
You have not binded anything to the input so of course there is nothing coming for the text box. Study the example app it has really good example and study the basics of Angular input / output binding.

**Comment by mukeshphpdev** [comment]
do you have any example?

**Comment by sconix** [comment]
As I said example app has lots of examples :)
