### ISSUE TITLE
Feature Request: Alpha Channel

### ISSUE THREAD

**Issue by rohanrichards** [zefoy/ngx-color-picker#160]
CSS v4 supports alpha in hex values: [see here](https://drafts.csswg.org/css-color/#hex-notation).
Should be fairly trivial to add an alpha selector (0 -> 100%) and convert to hex for the hex string, providing both rgba(r,g,b,a) and hex #rrggbbaa as outputs.

**Comment by sconix** [comment]
There is already support for alpha hex values.

**Comment by rohanrichards** [comment]
How? Theres no UI element as far as I can see

**Comment by sconix** [comment]
You just set the output to hex and force alpha channel with the configuration. Then the output is alpha hex values and there will be an alpha slider in the dialog.

**Comment by rohanrichards** [comment]
Will look more into config then must have missed it

**Comment by rohanrichards** [comment]
@sconix I cannot see any way to 'force alpha channel with the configuration' can you please clarify?
