### ISSUE TITLE
Showing only Preset Colors

### ISSUE THREAD

**Issue by ochadenat** [zefoy/ngx-color-picker#164]
Hi,

First, thank you for this great component. 

Would it possible to add a new parameter to show only the Preset Colors? I do not want the user to be able to choose a color that is not in the Preset Colors (See screenshot attached)

![image](https://user-images.githubusercontent.com/31458833/52522802-3b96e600-2c58-11e9-9520-1d7d661d7360.png)

**Comment by sconix** [comment]
You can always hide unwanted components with css.

**Comment by ochadenat** [comment]
Thanks for the suggestion. I added the following css code to achieve what I wanted:

```
.color-picker .saturation-lightness {
  display: none !important;
}

.color-picker .hue-alpha {
  display: none !important;
}

.color-picker .hex-text {
  display: none !important;
}

.color-picker .type-policy {
  display: none !important;
}
```

**Comment by AbdulWahabAchakzai** [comment]
I want to implement the same thing in my project and it does not work for me, I have installed ngx-color-picker from npm. 
can you guide?
