### ISSUE TITLE
Prevent closing the color picker when clicking outside the color picker.

### ISSUE THREAD

**Issue by meiuqer** [zefoy/ngx-color-picker#166]
I'm trying to implement this by doing a preventDefault on a global mousedown event but it's not working. Is there a way i can implement this myself? I might be overlooking something? 

Basically i want to only close the editor with the cancel and ok button. Is that possible?

**Comment by sconix** [comment]
I would say that the easiest is to add an transparent element that fills the whole view and is just below the dialog and catch click event from there and prevent their propagation. Other option could be to use the cpIgnoredElements.

**Comment by meiuqer** [comment]
Thanks i'll try that. Though it does looks cumbersome. Maybe it would be better to add a property? Same as cpSaveClickOutside?

**Comment by sconix** [comment]
Jeah I can add a property at some point, but atm I am really busy so no promises when I'll make a next release. At the latest when Angular 8 is out.

**Comment by meiuqer** [comment]
Thanks a bunch! In the mean time i'll fiddle around in the code myself.

**Comment by directcuteo** [comment]
Is this issue fixed? I am trying to stop the color picker being closed on outside click using [cpCloseClickOutside]="false" but the color picker closes no matter what value this Input takes.

**Comment by directcuteo** [comment]
Seems that I understand something wrong and implemented it wrong. Now it is working for me also.
