### ISSUE TITLE
color picker position issue

### ISSUE THREAD

**Issue by niccoicco9** [zefoy/ngx-color-picker#168]
i have a little problem as you can see with the following images:
![Cattura](https://user-images.githubusercontent.com/36620306/54133293-18f21b80-4416-11e9-9b16-4f3c26dbb246.PNG)
![Cattura2](https://user-images.githubusercontent.com/36620306/54133295-1b547580-4416-11e9-8ddd-1f5afd23074e.PNG)
the popup dialog appears under one more input and not in the origin input, for example if i click on color input the dialog appears under color 2 and if i click on colore2's input the dialog appears under ordinamento. i can fix this problem?

this is the code

 
        <ion-item>
          <ion-label>
            Colore 
          </ion-label>
          <ion-input cpOutputFormat="hex" formControlName="ColorHex" [style.background-color]="variant.ColorHex2"
            cpPositionOffset="50%" [(ngModel)]="variant.ColorHex" cpHeight="200px" cpDialogDisplay="popup"
            [(colorPicker)]="variant.ColorHex" cpPosition="bottom">
          </ion-input>
        </ion-item>`

        <ion-item >
          <ion-label>
            Colore 2
          </ion-label>
          <ion-input cpOutputFormat="hex" formControlName="ColorHex2" [style.background-color]="variant.ColorHex2"
            cpPositionOffset="50%" [(ngModel)]="variant.ColorHex2" cpHeight="200px" cpDialogDisplay="popup"
            [(colorPicker)]="variant.ColorHex2" cpPosition="bottom">
          </ion-input>
        </ion-item>

**Comment by sconix** [comment]
I see you have other style issues as well or you have used some custom styles. So I would look into fixing the styles of the dialog, you have either some styles "leaking" that cause issues for the dialog. In any case your issue should be fixable by fixing the styles.

**Comment by niccoicco9** [comment]
how you can see that i have style issues?

**Comment by sconix** [comment]
The dialog does not look as it should.

**Comment by niccoicco9** [comment]
yea i can fix with the css if i give a class to color picker dialog example:
 
```
<ion-input class="color-picker" cpOutputFormat="hex" formControlName="ColorHex" [style.background-color]="variant.ColorHex2"
        cpPositionOffset="50%" [(ngModel)]="variant.ColorHex" cpHeight="200px" cpDialogDisplay="popup"
        [(colorPicker)]="variant.ColorHex" cpPosition="bottom">
      </ion-input>

```

the css does not take it into consideration how i can add css properties to the dialog??

**Comment by sconix** [comment]
You style the classes the dialog uses i.e. just normally override the styles in the classes the dialog uses.

**Comment by niccoicco9** [comment]
i set in my scss page:

```
.color-picker {
    width: 10px!important;
}
```

but but does not overwrite the default style inside color-picker-component.css : 

`.color-picker {
  position: absolute;
  z-index: 100000;

  width: 230px;
  height: auto;
  border: #777 solid 1px;

  cursor: default;

  -webkit-user-select: none;
  -khtml-user-select: none;
  -moz-user-select: none;
  -ms-user-select: none;

  user-select: none;
  background-color: #fff;
}`

**Comment by niccoicco9** [comment]
i can't overwrite css because i have shadow dom with ionic 4, any other ideas?

**Comment by sconix** [comment]
Not sure how the shadow dom prevents that, but that's the only idea from me. Without any reproduction I can not do anything else.

**Comment by niccoicco9** [comment]
resolved!! the problem was the ion-list that have a default style

**Comment by sconix** [comment]
Good that you got it figured out.
