### ISSUE TITLE
[Bug] Violation warning on event listener

### ISSUE THREAD

**Issue by PsychoSTS** [zefoy/ngx-color-picker#17]
I am not able to drag any of the color picker handles in chrome (version 58.0.3029.110). With a bit of testing I also found that this is only an issue in chrome and not in Firefox or IE. 

I did some research online and found that it might be related to the following violation warning printed in the developer tools:

[Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive.

The above mentioned warning is printed every time I open up a color picker dialog.

Things I already tried in the code of the color picker:
* Tried the passive: true annotation on all addEventListener calls.
* Tried to remove any preventDefault calls.

**Comment by sconix** [comment]
Have you tried passive: false? Thats how it should be i.e. then it should be the same than before the change that was done in Chrome couple versions ago (they changed the default to true for the passive). For some reason I don't have this issue with the same Chrome version, but I have patched couple of other libs with passive: false to get them working. If you can verify that passive: false would work I can include it in the next release which I plan to make in couple of days.

**Comment by PsychoSTS** [comment]
I have just tried passive: false but my suborn chrome is still giving the same violation warning.  What I can tell you however is that it seems like the dragging is working but the UI is not getting updated. I dragged one of the sliders to a position, then the other. The moment I start dragging the other slider handle the previous one jumps to the drag position I dragged it to.

Maybe I am just missing something here I don't know. I have been playing around with the source all day and cannot seem to pin down the exact problem or a solution yet. I will continue my search...

**Comment by sconix** [comment]
Ok that changes things, so its a change detection problem. Not sure how you can get it into such state unless you have been changing the change detection strategy. Are you only getting this behavior in your own application or in the example as well?

**Comment by PsychoSTS** [comment]
I am getting the same behavior in my application, the example and the online demo. I am glad that gave you the correct info.

**Comment by PsychoSTS** [comment]
I would like to provide some feedback on what happened on my side. The problem was in the end not related to your library at all. I had to clean my chrome cache and history before I had to close the whole chrome service on my PC. After doing all of this the example and demo started to work perfectly.  

Thank you for the help yesterday!

**Comment by specchiasoft** [comment]
I have exatly  now this issue with Angular 9 &  "ngx-color-picker": "^9.0.0",  this is input:
`<input formControlName="Color" [(colorPicker)]="Color.value" [style.background]="Color.value"
                [cpOKButtonClass]="'btn btn-primary px-3'" [cpOKButton]="true" [cpSaveClickOutside]="false"
                (colorPickerChange)="form_group.get('Color').setValue($event)">`

and  every time i get focus in Color field, i receive this warning in console repeated 4 times :
`[Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive.`
