### ISSUE TITLE
(colorPickerSelect) on outside click

### ISSUE THREAD

**Issue by jacobbutton** [zefoy/ngx-color-picker#170]
Shouldn't (colorPickerSelect) be emitted on outside click if [cpSaveClickOutside] is set to true (which it is by default)?

**Comment by sconix** [comment]
Not really, if you are not using select button then every color change is "final" so you only need the color change event or depending on the use case maybe dialog closed event. So the select event is only used for the select button atm.

**Comment by jacobbutton** [comment]
> Not really, if you are not using select button then every color change is "final"

Yea. I don't want it to be. I want the user to be able to cancel the colorPicker and preserve the original color, but I also want an outside click to save the currently selected color. As it stands now I see no way of enabling [cpSaveClickOutside] and having a cancel button. If the cancel event emitted before the close event, or canceling prevented the close event, then maybe it would be possible, but since close emits before cancel, any logic in the close event (such as updating data to the backend) fires before the cancel event has a chance to stop it.  The easiest solution I see is having colorPickerSelect emit on outside click when [cpSaveClickOutside] is enabled.

**Comment by sconix** [comment]
But doesn't the cancel emit the color that was selected when dialog was opened? At least it should so afaik in your case you just always store the what ever color is emitted and it works as it should.

**Comment by jacobbutton** [comment]
Cancel does emit the original color, but it fires after the close event which makes it worthless in preventing logic inside the close event - say an async call to the api - from happening. Sure, I could always send a second api call on the cancel event to change the color back to what it was originally, but why send two api calls when you don't need to send any.

All that being said, it doesn't really matter. If you have a (colorPickerSelect) event that emits the final color selected, logically it should emit the final color selected in all UI paths that select a final color, which includes an outside click when [cpSaveClickOutside] is turned on.

**Comment by sconix** [comment]
Ok so you want to optimize the api call counts, now I see. I will have to think a bit if using the select event is the best solution, but most likely it is. Currently I am very busy, but I will try to have time to address this within 1-2 weeks. In the meanwhile PR's are naturally accepted as well.

**Comment by sconix** [comment]
The next version 7.5.0 which is out soon will send colorPickerSelect event on close when the cpSaveClickOutside is true.
