### ISSUE TITLE
Touch Devices: Color Picker Dropdown doesn't close when tapped outside

### ISSUE THREAD

**Issue by bhaskerchari** [zefoy/ngx-color-picker#174]
Color picker doesn't close automatically when tapped outside in touch devices. I have verified in Ipad and mobile devices.

I believe ngx-color-picker is relying on mousedown event to close the color picker dropdown internally which may not work in Touch Devices.

**Comment by sconix** [comment]
I'll add touch support listening for next release.

**Comment by bhaskerchari** [comment]
@sconix ,

Thanks for the update, will look forward for the release.

Thanks,
Bhasker
