### ISSUE TITLE
Order of firing of events

### ISSUE THREAD

**Issue by dioseltorre** [zefoy/ngx-color-picker#177]
I think it's logical to fire first **colorPickerSelect** event before **colorPickerClose**. It is useful in some cases in which we want to have some checking just when the picker is closed whether it is clicked outside or clicking **Cancel** and **OK** button.
Currently, **colorPickerClose** is fired before **colorPickerSelect**.

What do you think?

**Comment by sconix** [comment]
Select should be fired before close at least thats how its in code. In what situation you are seeing this?

**Comment by dioseltorre** [comment]
I just have this config in my case:
```html
<span [cpPosition]="'bottom'"
[cpPositionOffset]="'50%'"
[cpOKButtonClass]="'cp-btn ok'"
[cpCancelButtonClass]="'cp-btn cancel'"
[cpCancelButtonText]="'PAGES.CANCEL' | translate"
[cpOKButton]="true"
[cpCancelButton]="true"
[cpSaveClickOutside]="false"
[cpPositionRelativeToArrow]="true"
[cpFallbackColor]="'#ffffff'"
[(cpToggle)]="bgColorToggle"
[(colorPicker)]="textBgColor"
(colorPickerSelect)="onSelectBgColor($event)"
(colorPickerClose)="onCloseBgColorPicker()">
</span>
```

Nothing fancy in my code I just wrote console log in select and close handlers. It seems close event was fired first as seen in the console log below.

![image](https://user-images.githubusercontent.com/14935048/58005180-071cab00-7b20-11e9-843e-588e6282c72e.png)

**Comment by dioseltorre** [comment]
I just checked on the code and it really does fire the close event first since I'm using the default dialog display.

```javascript
public onAcceptColor(event: Event): void {
    event.stopPropagation();

    if (this.cpDialogDisplay === 'popup') {
      this.closeColorPicker();
    }

    if (this.outputColor) {
      this.directiveInstance.colorSelected(this.outputColor);
    }
}
```

**Comment by sconix** [comment]
Ah you mean when the OK button is pressed. That seems to be the case that it has the wrong order. Will fix for the next release.

**Comment by dioseltorre** [comment]
Yes. When clicking the OK button.
Thanks for the quick response.
