### ISSUE TITLE
cpPositionOffset doesn't seem to be working

### ISSUE THREAD

**Issue by rohanrichards** [zefoy/ngx-color-picker#180]
I can't get the cpPositionOffset property to work, have tried many combinations of strings. It doesn't appear to be working in the example app either
https://zefoy.github.io/ngx-color-picker/

**Comment by sconix** [comment]
Works for me. Can you tell me your browser and perhaps include a screenshot to avoid misunderstanding about the issue.

**Comment by rohanrichards** [comment]
Ah I think I understand now, I was expecting it to offset relative to the parent (creating whitespace if required)
I have this issue: 
![Capture](https://user-images.githubusercontent.com/16222002/58672096-ae070f80-8388-11e9-8c51-c15013aa21f9.PNG)
That I was hoping to solve by forcing it to be displayed further to the left (but still on top). But I guess offset only controls its position within the bounds of the parent?

Any recomendation on how I might solve the above problem? I can't simply put it on the left, as it would then be drawn too low and be obscured by the bottom of the page (same problem again, I cant just offset it up a touch)
I guess I'm looking for a "top left" option realistically.

**Comment by rohanrichards** [comment]
I didn't think to just do something like "-400%" and I've got it appearing on screen, however the arrow refuses to stay where It should, even with `cpPositionRelativeToArrow` toggled true or false
![Capture](https://user-images.githubusercontent.com/16222002/58672280-882e3a80-8389-11e9-847b-6bde6e944158.PNG)

Is there any solution to this?

**Comment by sconix** [comment]
You can always style the dialog as you wish with CSS, so you can just add negative margins or transforms  to the whole dialog or to the arrow etc.

**Comment by rohanrichards** [comment]
> 
> 
> You can always style the dialog as you wish with CSS, so you can just add negative margins or transforms to the whole dialog or to the arrow etc.

Good idea, thanks! I was contemplating a PR that might negate the offset variable on the triangle so that it was always over the origin...but I don't think I've got the spare time.
Will close this though as there's actually no issue here, thanks for the quick and helpful replies everyone, and thank you for the fantastic module!
