### ISSUE TITLE
Hide/Show Color Options

### ISSUE THREAD

**Issue by Rlcolli4** [zefoy/ngx-color-picker#182]
I think this color picker is great, a feature that would be great for our use case is the capability to either choose which color options are usable or  which ones are not usable.

This is what I am thinking:
`cpAvailableOptions=['rgba','hex','hsla']` //default
The use would just pass in an array of options they want to use. (IE `['rgba','hex']`)
--OR--
`cpHideOptions`=[] // default
The use would just pass in an array of options they do not want to use. (IE `['hsla']`)

Our use case for the color picker is to allow the user to use rgba or hex values for their colors, while we can control the output value, we don't want to show them the hsla as many of our users will not be familiar with it and we don't want to confuse them with it.

**Comment by sconix** [comment]
I do not believe having all the options causes any confusion to users. They will anyway have to understand the fact that they are different color formats so not understanding all the formats is not a problem for the user. So I do not see this as a problem at all so as long as we do not receive any freedback from our users (so far there has been no usability complaints for the color picker) I won't be adding such option. Of course this does not mean that I am not open for such feature so if PR is presented I will gladly include it.

**Comment by Rlcolli4** [comment]
Sorry, haven't looked at this in a while. Did not mean to let this clutter your issues board. It's not been a big issue, so until we hear it's an issue for our users we will do a PR. I'll close this in the mean time.
