### ISSUE TITLE
Showing two preset colors list

### ISSUE THREAD

**Issue by iamdebodon** [zefoy/ngx-color-picker#184]
Hi @sconix  ,

I have a requirement where I need to update two preset color arrays where I can show two sets of color pallets, one with the user selection and the other will be default color pallets.

Something similar to the below image

![preset colors](https://user-images.githubusercontent.com/38261932/59085772-5256fc00-891d-11e9-8794-7857b555c4dd.JPG)

Thanks.

**Comment by sconix** [comment]
If you have a fixed number of basic colors you want there I think you should be able to do that with CSS.

**Comment by iamdebodon** [comment]
I doubt, we can do that or not, as we are simply passing the preset colors array. And how to do the breakdown and update the preset color list.

**Comment by sconix** [comment]
I do not see any issues if you just have fixed amount of those default colors. Even if it would be dynamic you could do it with dynamic styles, but that gets naturally bit trickier.
