### ISSUE TITLE
[cpPosition]="'top'" works after window resize

### ISSUE THREAD

**Issue by PawelWalnik** [zefoy/ngx-color-picker#185]
Setting [cpPosition] to 'top' causes the following:
![obraz](https://user-images.githubusercontent.com/21141285/59347113-228c6780-8d14-11e9-8742-34719d8e0114.png)

Then when I change the window size it goes to correct position:

![obraz](https://user-images.githubusercontent.com/21141285/59347208-549dc980-8d14-11e9-9080-12abad0ea2ed.png)

It happens inside and outside the modal. I tried to put color input in different places and containers and bug always occurs.

cpPositionRelativeToArrow has no affect on color picker correct popup positioning.

_Tested on Mozilla Firefox 67.0.1_

**Comment by sconix** [comment]
I was able to reproduce this, will fix it for next release. Thanks for reporting this.

**Comment by PawelWalnik** [comment]
Thanks :)
