### ISSUE TITLE
Regarding the preset colors

### ISSUE THREAD

**Issue by candorthor** [zefoy/ngx-color-picker#190]
@zefoy

I need only the preset to be poped up. I do not need the rest portion of the popup. Could you please help in solving this. Screenshot attached for your reference.
![image](https://user-images.githubusercontent.com/49184671/60443357-b6c55c80-9c38-11e9-8e4d-da21507b7fe9.png)

**Comment by sconix** [comment]
You can easily style the dialog as you wish with CSS so just hide anything youndo not want to be shown.

**Comment by candorthor** [comment]
@sconix 

Do we any option to move the parameter "[cpPresetColors]="['#ffffff', '#FF0000', '#2889e9', '#e920e9', '#fff500', '#00FF00', '#800000', '#800080']" to ts fie?

![image](https://user-images.githubusercontent.com/49184671/60479548-d2198180-9ca3-11e9-8516-b995265b1704.png)

**Comment by sconix** [comment]
Sure its normal Angular binding nothing special.

**Comment by candorthor** [comment]
@sconix 

Could you please show how this can be done?

**Comment by DebuggerAK** [comment]
*.html
`[cpPresetColors]="presetColors" `

*.ts
`public presetColors = ['rgba()', 'rgba()', 'rgba()', 'rgba()', 'rgba()', 'rgba()'];`

**Comment by candorthor** [comment]
@DebuggerAK ,

Thanks a lot for your help.
