### ISSUE TITLE
Color picker jumps from the bottom to the correct location on first open

### ISSUE THREAD

**Issue by AliakseiLabkovich** [zefoy/ngx-color-picker#193]
Hi. I'm currently experiencing an issue when color picker window jumps quickly from the bottom of the component to the correct location when you open it for the first time. 
![ezgif-5-5ba04a45136f](https://user-images.githubusercontent.com/40228491/61371734-2aed3a80-a89e-11e9-9c58-631cf97e4235.gif)
You can easily reproduce it on the StackBlitz page in any example, but https://zefoy.github.io/ngx-color-picker/ works fine. Is there some difference between the two pages that causes the flickering to appear? Or maybe this is a bug.

**Comment by sconix** [comment]
This was fixed in the release I made today.
