### ISSUE TITLE
using cpUseRootViewContainer inside dialog

### ISSUE THREAD

**Issue by ymchun** [zefoy/ngx-color-picker#201]
seems dialog cannot inject app instance and get error as following:

```
Error: NullInjectorError: No provider for AppComponent!
```

Is there a way to use `cpUseRootViewContainer` option inside dialog?
Or can support accepting the app instance via input?
Since the color picker is clipped inside the dialog content.

![3BD5C4BE-29F6-444B-B76A-B275EC0FD88F](https://user-images.githubusercontent.com/282311/64714483-49b02c00-d4f1-11e9-8b64-78837f9a37c3.jpeg)

**Comment by sconix** [comment]
Do you have public ViewContainerRef exposed in your root (app) component with the name of vcRef or viewContainerRef?

**Comment by ymchun** [comment]
> Do you have public ViewContainerRef exposed in your root (app) component with the name of vcRef or viewContainerRef?

even I added `public vcRef: ViewContainerRef` or `public viewContainerRef: ViewContainerRef` to root component, still the same error.

**Comment by ymchun** [comment]
example for the bug: https://stackblitz.com/edit/angular-ropcaj

**Comment by sconix** [comment]
At least that example has normal Angular errors related to missing providers nothing related to this library.

**Comment by ymchun** [comment]
any suggestion to solve the clipping inside dialog content, please?

**Comment by sconix** [comment]
Using the cpUseRootViewContainer usually helps or just fix the styles so there is no clipping if it won't break the dialog.

**Comment by CFT-Chris** [comment]
I encountered the same issue. Debugged it, found out that the injector for the dialog component cannot get root app component as it traces up its branch of the DI tree. The ngx-color-picker directive code throws an error on line [159](https://github.com/zefoy/ngx-color-picker/blob/master/src/lib/color-picker.directive.ts#L159).

I made a PR to make a fallback for our cases.
