### ISSUE TITLE
Incorrect color picker position

### ISSUE THREAD

**Issue by nileshbhagwat** [zefoy/ngx-color-picker#202]
Provided picker position as 'top-left' in stackblitz, still picker positioned for 'top-right'

![image](https://user-images.githubusercontent.com/22997240/65051294-7f886100-d986-11e9-9056-19e30eab61b5.png)

Seems only this position works fine: 'top', 'bottom', 'left', 'right',
For other positions ('top-left', 'top-right', 'bottom-left', 'bottom-right'): Picker position is 'top-right' only

**Comment by sconix** [comment]
I could swear that I tested it before the previous release, but indeed those seem to be broken. I will make bug fix release soon.

**Comment by sconix** [comment]
The Stackblitz seems to be using old version of the library. Thats why its not working.

**Comment by nileshbhagwat** [comment]
@sconix, thanks. Working now. 
Closing issue.
