### ISSUE TITLE
Allow nullable color values to be null when dialog is closed via cancel and previous value was null

### ISSUE THREAD

**Issue by chibibiscuit** [zefoy/ngx-color-picker#203]
In my use case, I have an optional setting where a user's default annotation color can be selected. If that field is null (which in this scenario is a valid value), then it assumes the user has no default color, and it defers to a series of intelligent defaults until it finds a place where this is set. As it is an override, we do not save a value to our database for every user - instead, we are only storing values which are not null.

The issue with the current behavior is that if you open up the color picker when the starting color is null, and then decide to cancel out of it so as to leave the input at its original color (null), it will choose to set the color anyways.

I'm encountering the current behavior:

1. The initial value of the input is `null`, open the color picker.
2. After opening the color picker, select the color red.
3. Close the color picker, using either the cancel button or by clicking outside the dialog. 
(Note that `cpSaveClickOutside` is set to false)
4. The value of the input is now set to red, despite the fact that the original color before the dialog was opened was null. 

I believe that in this scenario, since the act of choosing a color was cancelled, the value should be returned to it's previous value - even if that value is null.

I have set up a Stackblitz illustrating this behavior:
https://stackblitz.com/edit/github-czm8hb

**Comment by sconix** [comment]
I guess this is rather easily doable, but not sure when I have the time. In the meantime PR's are accepted.

**Comment by chibibiscuit** [comment]
I spent some time this morning pulling down the repo, unfortunately npm install would crash every time when trying to run npm run bundle. I do think it'd be easy, but being unable to run or test my changes, I'll hold off on putting up a PR and go with your suggestion of listening to the on cancel event.

**Comment by chibibiscuit** [comment]
Okay, so I did hook into the cancel event, but this brings up a different issue (and if you'd like, I can create a new issue for it) - if the ColorPicker dialog is closed by clicking outside of it, when `cpSaveClickOutside` is set to false, this action does not trigger the OnCancel emitter, even though it is essentially performing the cancel functionality.

**Comment by sconix** [comment]
That sounds like a bug so you can make a separate issue about that.

**Comment by sconix** [comment]
Both of these issues should be fixed with the 9.0.0-2 release.
