### ISSUE TITLE
Opening the dialog programatically 

### ISSUE THREAD

**Issue by gcherem** [zefoy/ngx-color-picker#211]
First of all, congratulations for the excelent component!

I need to open the color picker dialog programatically, I mean, from a (click) event from other component. How can I do that? 

Thanks in advance and keep up the good work!

**Comment by CharlyRipp** [comment]
Isn't that the `[(cpToggle)]`?

Snippet from example StackBlitz
```
<input #ignoredInput
       [style.background]="color"
       [cpIgnoredElements]="[ignoredButton, ignoredInput]"
       [(cpToggle)]="toggle"
       [(colorPicker)]="color"/>

<button #ignoredButton (click)="toggle=!toggle"></button>
```

> from other component

I'd suggest `@Input()` variable into this component and control the value from outside. Would probably want to report back to parent component via `@Output()` ie:

```
  _pickerOpen: boolean;
  @Output() pickerOpenChange = new EventEmitter<boolean>();
  @Input()
  set pickerOpen(open: boolean) {
    this._pickerOpen = open;
    this.pickerOpenChange.emit(this._pickerOpen);
  }
  
  get pickerOpen() {
    return this._pickerOpen;
  }
```

and just reference `pickerOpen`, letting the getter/setter do the lifting.
