### ISSUE TITLE
Adding an alpha picker only

### ISSUE THREAD

**Issue by Crocsx** [zefoy/ngx-color-picker#221]
Hello, 

I was trying this library, and it looks really nice.

But I have a question/request. It appears to me that it's not currently possible to have a single alpha picker at the moment ? 

Something like :

`[cpColorMode]                // Dialog color mode: 'color', 'grayscale', 'presets', 'alpha' ('color').`

So that would only show only the alpha picker that is currently available, but without any color.

**Comment by Crocsx** [comment]
Ok so it is not hard to do :

.html
```
    <div class="setting no-color" (click)="$event.stopPropagation()" >
      <input 
        (click)="$event.stopPropagation()" 
        (colorPickerChange)="onOpacityChange('mainImageryAlpha', $event)"
        [cpOutputFormat]="'rgba'" 
        [cpDisableInput]="'true'"
        [colorPicker]="'rgba(0,0,0,'+settings.mainImageryAlpha+')'"
        [style.background]="'rgba(0,0,0,'+settings.mainImageryAlpha+')'" 
        class="setting_colorPicker setting-input"/>
    </div>
```
.less
```
.no-color {
    .saturation-lightness{
        display:none !important;
    }
    
    .hue{
        display:none !important;
    }
}
```

and you just change the alpha of the variable in code.

But I believe a simple alpha picker without having to do all this would be a great plus.

**Comment by sconix** [comment]
I have no plans of adding such features that can be done using styles due to wanting to keep the code as simple and maintainable as possible.
