### ISSUE TITLE
Close event is fired before cancel event.

### ISSUE THREAD

**Issue by spockoyno** [zefoy/ngx-color-picker#226]
When the Cancel button is called in the pop-up mode, the close event precedes the cancel event. It's a problem in my case, as the cancelled operation (adding a row on the screen) still happens. 

This is very similar to  issue #177. 

Just in case, here's the code

`
<span
      class="add"
      *ngIf="fullDisplay$ | async"
      [style.color]="palette.newColour"
      [cpPosition]="'bottom'"
      [cpPositionOffset]="'50%'"
      [cpDisableInput]="true"
      [cpCancelButton]="true"
      [cpPresetLabel]=" '' "
      [cpPositionRelativeToArrow]="true"
      [cpPresetColors]="presetColours"
      [(colorPicker)]="palette.newColour"
      (colorPickerOpen)="colourPickerOpened()"
      (colorPickerCancel)="colourPickerCancel()"
      (colorPickerClose)="pickerClosedWithColour($event)"
      [cpCancelButtonClass]="'btn mat-raised-button btn'">
      <b>ADD COLOUR</b>
    </span>
`

**Comment by sconix** [comment]
You are right will release a bug fix release.

**Comment by sconix** [comment]
This should be fixed in the 9.1.0 release.

**Comment by spockoyno** [comment]
Thanks a lot! Great library by the way. Very handy for my covid epidemiology app.
