### ISSUE TITLE
Add support for cmyk format

### ISSUE THREAD

**Issue by lebsral** [zefoy/ngx-color-picker#23]
Is there any plans to support cmyk in addition to rgb?

Are you accepting pull requests?

**Comment by sconix** [comment]
Not high on my list, but why not. PR's are of course accepted.

**Comment by bubba5656** [comment]
CMYK support is a requirement for a printing project. 
 I need to keep track of the color mode and emit colors in that mode i.e RGB, or CMYK, as the user cycles thru arrow. The current design returns RGB or HEX, as defined in color-picker-service outputFormat function. In CMYK mode we need to emit CMYK output, especially when the user has manually entered CMYK values. Converting those values to RGB and back to CMYK will introduce conversion errors. I also want the ability to customize the color spaces ex: no HEX or HSV. The programmer can pass in the required color spaces.

I have created a fork and added CMYK support. see below.  If you are interested in adding this feature as PR please let me know.

![image](https://user-images.githubusercontent.com/49929884/56822682-c92daf00-681f-11e9-9882-071fea1d7813.png)

**Comment by sconix** [comment]
Sure I can add it as a feature if you make a PR.

**Comment by bubba5656** [comment]
I have added support for CMYK and the following is an updated example which shows the CMYK colors chosen. 

[cpOutputFormat]="'cmyk'"  can be specified as new option 

changes can be observed with
(cpCmykColor)="setCmyk($event)" 

![image](https://user-images.githubusercontent.com/49929884/57039743-798a2180-6c2b-11e9-80c9-f01411132a46.png)

![image](https://user-images.githubusercontent.com/49929884/57039891-e6052080-6c2b-11e9-8f7c-c5fc9d0a186e.png)

**Comment by bubba5656** [comment]
@sconix 

Will you be pulling the changes I made any time soon?

**Comment by sconix** [comment]
I just got back from my holiday so as soon as I have had time to unload my work stuff I will merge the PR.

**Comment by bubba5656** [comment]
@sconix 
Thanks
