### ISSUE TITLE
Auto position, not working

### ISSUE THREAD

**Issue by DerekJDev** [zefoy/ngx-color-picker#231]
I have cpUseRootViewContainer=true and I verified that there aren't any styles other the the styles included with this library affecting the position. I have the overflow on the body and html tag set to hidden as well. The color-picker element is getting place right outside the app-root tag, but it doesn't seem to detect the edges of the body. Thanks in advance for the help. Here's my input:

`<input matInput [colorPicker]="color" (colorPickerChange)="onChange($event)" [(cpToggle)]="toggle" [value]="color"
      [cpOutputFormat]="'hex'" [cpPresetColors]="pageColors" [cpPresetLabel]="'Page colors'" [cpPosition]="'auto'"
      [cpAlphaChannel]="'disabled'" [cpIgnoredElements]="['transparent']" [cpUseRootViewContainer]="true" readonly="true"
      style="cursor: pointer;" />`

![PositionBug](https://user-images.githubusercontent.com/13419128/82297702-47e81380-9970-11ea-91da-223a29895614.jpg)

**Comment by DerekJDev** [comment]
@zefdevel Is this repo no longer being maintained?

**Comment by sconix** [comment]
It is, but currently I have no time for new features. There is no proper auto position support yet only very simple version provided via PR. I am on the fence that should I bring in the material CDK library or not for making a proper auto positioning.
