### ISSUE TITLE
TypeError: Cannot read property 'nativeElement' of undefined

### ISSUE THREAD

**Issue by KGupta13** [zefoy/ngx-color-picker#235]
I am getting following error, when clicking - on input colorpicker-box and not able to select the color.

ERROR TypeError: Cannot read property 'nativeElement' of undefined
    at ColorPickerComponent.push../node_modules/ngx-color-picker/__ivy_ngcc__/dist/ngx-color-picker.es5.js.ColorPickerComponent.ngOnInit (ngx-color-picker.es5.js:1074)

**Comment by Crocsx** [comment]
I have same problem since I updated to angular 9, but not in all of my color picker. 

I am looking for a solution

**Comment by Crocsx** [comment]
If I have time I will make a reproducible exemple,

but in my project, It looks like the problem happens when the color picker is used inside a div using `*ngIf` set to false (then switched to true)

**Comment by Crocsx** [comment]
In my case it was due to the fact that I was drawing a tooltip on the picker element : 

```
            <input
              matTooltip="{{ 'MAP.LAYERS.LAYER_COLOR' | translate }}"
              (colorPickerChange)="setOpacity(addedLayers.get(layer.id), $event)"
              [cpOutputFormat]="'rgba'"
              [cpDisableInput]="'true'"
              [colorPicker]="'rgba(0,0,0,' + addedLayers.get(layer.id).alpha + ')'"
              [style.background]="'rgba(0,0,0,' + addedLayers.get(layer.id).alpha + ')'"
              class="button full-width"
            />
```

removing the tooltip made it work again.

**Comment by MasterBroki** [comment]
I checked the error on my side, it is due to an incorrect use of ngOnInit calling ViewChild properties. I'm working on a fix

**Comment by KGupta13** [comment]
Thanks for the response and fixing the bug, but after updating the latest version this error was gone.

________________________________

**Comment by MasterBroki** [comment]
Cool, can you give your angular version and color picker version?
