### ISSUE TITLE
ColorPickerModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy

### ISSUE THREAD

**Issue by MatthewLHolden** [zefoy/ngx-color-picker#247]
` ERROR in node_modules/ngx-color-picker/lib/color-picker.module.d.ts:1:22 - error NG6002: Appears in the NgModule.imports of ThemeEditorModule, but could not be resolved to an NgModule class.`

--

`This likely means that the library (ngx-color-picker) which declares ColorPickerModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.`

Steps:

1. npm install ngx-color-picker --save
2. import { ColorPickerModule } from 'ngx-color-picker'; added to a module
3. Build

Is there a way around this?

**Comment by MatthewLHolden** [comment]
Update: This error only appears if the module is added whilst `ng serve` is active. If that's cancelled, and the rebuilt, it appears to work fine.

**Comment by sconix** [comment]
Thats how Angular cli works, it processes the libraries on build time.

**Comment by MatthewLHolden** [comment]
Yup, I'll close. I just hadn't experienced that with any other modules i added. But i've recently changed to the newer version of Angular, so it could just be apparent since then. Cheers.
