### ISSUE TITLE
Arrow not displayed on angular 10

### ISSUE THREAD

**Issue by kevinLourencoDev** [zefoy/ngx-color-picker#249]
Hi,

I think the migration on angular 10 broke the arrow. It's not showing anymore and is replaced by a black square on the top corner. It's just missing calculation for setting the style of the arrow. 

You can see it directly on the demo of the project: [https://stackblitz.com/github/zefoy/ngx-color-picker/tree/master](https://stackblitz.com/github/zefoy/ngx-color-picker/tree/master)

Are you already working on it?

<img width="76" alt="Capture d’écran 2020-11-05 à 16 12 56" src="https://user-images.githubusercontent.com/45124458/98259223-244a7100-1f82-11eb-9248-263d8a6ce66d.png">
<img width="96" alt="Capture d’écran 2020-11-05 à 16 13 28" src="https://user-images.githubusercontent.com/45124458/98259227-257b9e00-1f82-11eb-956b-107192900b54.png">
<img width="265" alt="Capture d’écran 2020-11-05 à 16 13 43" src="https://user-images.githubusercontent.com/45124458/98259230-257b9e00-1f82-11eb-90b3-f31b538507c0.png">

cc @sconix

**Comment by DaGLiMiOuX** [comment]
Im having the same problem with Angular 7

**Comment by sconix** [comment]
I will have a look this weekend if I can find the bug and fix it.

**Comment by kevinLourencoDev** [comment]
@sconix Any good news?

**Comment by sconix** [comment]
Latest trelease fixes this.
