### ISSUE TITLE
Ability to entirely hide text input fields in the color picker.

### ISSUE THREAD

**Issue by jonaswinkler** [zefoy/ngx-color-picker#262]
Hello!

Is it possible to hide the manual input fields? I've already got an input field for the color code, having that twice feels unneccesary to me.

Current state:
![image](https://user-images.githubusercontent.com/17569239/109079847-d3f94980-76ff-11eb-91e6-7954536fae08.png)

State I'd like to have:
![image](https://user-images.githubusercontent.com/17569239/109080103-4b2edd80-7700-11eb-8ef3-00996e743ced.png)

Thank you!

**Comment by sconix** [comment]
You can always do that with the CSS.

**Comment by jonaswinkler** [comment]
...

See, that's why I'll never get a job as a web dev. Thanks.
