### ISSUE TITLE
Changing color by editing the textbox within the popup

### ISSUE THREAD

**Issue by matt-potts** [zefoy/ngx-color-picker#265]
When engaging with the color picker, changing the color through the textbox returns an object instead of a hex string. The attribute **cpOutputFormat** is set to 'hex'. I tried updating from v9 to v11 and no change.

Framework: Angular 9
package version: 9.1.0

![image](https://user-images.githubusercontent.com/13987889/114095925-0c0db380-988c-11eb-9548-93f047d4ab5b.png)

![image](https://user-images.githubusercontent.com/13987889/114092471-ee3e4f80-9887-11eb-8ebb-4e9df4441aed.png)

I have a workaround in place but I thought I'd let you guys know.

**Comment by Rlcolli4** [comment]
Is this still an issue for you? I have not been able to replicate with the most recent code.

**Comment by Rlcolli4** [comment]
This may be more a matter of needing better documentation or requesting a feature. Looking into the actual code, any time you change the input in the popover box, it will always emit a object until you "submit" the change, at which it does output your set color. 

Going to the README.md you can learn how `cpInputChange` is intended to work without reviewing the code:
```
(cpInputChange)              // Input name and its value, send when user changes color through inputs
                                         // ({input: string, value: number | string, color: string})
```
`colorPickerChange` however does output a string, and in my mind should return what you put in the `cpOutputFormat`:
```
(colorPickerChange)          // Changed color value, send when color is changed (value: string).
```
From testing the code locally, I am seeing the correct behavior based on both those lines of code, but I do admit that the description of `cpOutputFormat` does not help clarify which inputs it should/should not effect.

**Comment by matt-potts** [comment]
To me, the format should be consistent across the board, whether typing or clicking, especially considering it's the same widget. However, it's documented, so that's on me. With that said, I agree with your statement about cpOutputFormat. I assumed setting it to 'hex' would make sure all outputs come as hex. It would help others to know it's only for colorPickerChange events. Thanks for responding to my post. I appreciate the feedback.

**Comment by matt-potts** [comment]
Closed as it's long past stale.
