### ISSUE TITLE
Incorrect behavior in HSLA mode when opacity not 1

### ISSUE THREAD

**Issue by tania-mel** [zefoy/ngx-color-picker#267]
It's possible to recreate the issue on demo page: https://zefoy.github.io/ngx-color-picker/

Open color picker and set opacity not 1. Switch to HSLA mode. Try to change H, S or L value. Picker will apply one entered character (for example I selected value in S and tried to change it to 55, then only 5 was applied as new value) and switch to RGBA mode.

**Comment by Rlcolli4** [comment]
I just submitted a merge request for this, we will see if they take it or not!
