### ISSUE TITLE
Can't bind to 'colorPicker' since it isn't a known property of 'input'.

### ISSUE THREAD

**Issue by Sathishchary** [zefoy/ngx-color-picker#27]
Its working in angular cli , but now I am converting my project to angular cli + angular universal. after  i got this error.
```
 <input [ERROR ->][(colorPicker)]="color" [style.background]="color" [value]="color"
```
```
import {ColorPickerModule} from 'ngx-color-picker';

@NgModule({
  imports: [ ColorPickerModule ],
  bootstrap: [AppComponent]
})
export Appmodule { }
```

**Comment by liebstein** [comment]
You need to define a shared module and export ColorPickerModule
`import { NgModule, ModuleWithProviders } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ColorPickerModule } from 'ngx-color-picker';



@NgModule({
  imports: [
    CommonModule,
    ColorPickerModule
  ],
  exports: [
    CommonModule,
    ColorPickerModule
  ],
  declarations: [],
  providers: []
})
export class SharedModule {

  static forRoot(): ModuleWithProviders {
    return {
      ngModule: SharedModule
    };
  }
}`

**Comment by marekdano** [comment]
@Sathishchary can you please describe how you implement this library in angular cli? I'm getting the error:
   "Cannot read property 'h' of undefined" 
when I hit the color input field.
Thanks.

**Comment by Sathishchary** [comment]
@marekdano , I followed @liebstein code only. created one share module,in that I have imported and exported color picker module . And last I imported that share module in app.module.ts file
I am using "ngx-color-picker": "^4.0.3",
angular -cli : 1.0.0
angular version: 4.0.0
Note: I am using this in cli only. I stopped working on angular universal
thanks

**Comment by jiggy1com** [comment]
I'm converting my SystemJS version to Angular-Cli
The SystemJS version works fine (using shared module as described above), but when I move my code to my cli version ng build --prod fails

> Error encountered resolving symbol values statically. Could not resolve ngx-color-picker relative to /[path-to-project]/src/app/shared/SharedModule.ts

I thought maybe I needed to add something like `"../node_modules/ngx-color-picker/dist/lib/index.js"` in the scripts prop of angular-cli.json

Getting late tonite, so I'll keep digging and testing things out tmrw or over the next few days. If anyone knows what I need to do please LMK. Thanks!

ng version =>
@angular/cli: 1.4.2
node: 6.11.2
os: darwin x64
@angular/animations: 4.4.1
@angular/common: 4.4.1
@angular/compiler: 4.4.1
@angular/core: 4.4.1
@angular/forms: 4.4.1
@angular/http: 4.4.1
@angular/platform-browser: 4.4.1
@angular/platform-browser-dynamic: 4.4.1
@angular/router: 4.4.1
@angular/cli: 1.4.2
@angular/compiler-cli: 4.4.1
@angular/language-service: 4.4.1
typescript: 2.3.4

**Comment by sconix** [comment]
with angular-cli you don't need to do any setup. Just import the library and load the module that should be enough.

**Comment by jiggy1com** [comment]
@sconix Yep. I was working out of 2 different directories (1 for sysjs 1 for cli) and forgot to npm install ngx-color-picker in the cli version. Did that and voila! Thanks for making me not overthink this.
