### ISSUE TITLE
Option to hide input fields inside the color picker

### ISSUE THREAD

**Issue by mvhecke** [zefoy/ngx-color-picker#28]
Right now there is no option to hide the input fields inside the color picker. I think it would be valuable to have the option to hide.

**Comment by sconix** [comment]
Maybe bit later, dont see it that valuable since you can do it with just one line via css styles. But yes maybe later on it would be useful to have simpler + slightly lighter color picker by having option to disable features.

**Comment by sconix** [comment]
For the next major version I will be adding a way to easily make custom color picker dialog so then its possible to use only wanted components. I keep this issue open until that.
