### ISSUE TITLE
Upgrade to angular 13 + Ivy

### ISSUE THREAD

**Issue by POFerro** [zefoy/ngx-color-picker#282]
Hi :),

Are there any plans to upgrade this library to support Ivy?
After upgrade to angular 13 there's a warning that this library is compiling using Legacy ViewEngine.

Thanks
POFerro

**Comment by magnusbakken** [comment]
Not sure if it's necessary, but I've created a pull request for the upgrade #283. There are some issues with package incompatibilities in the devDependencies. However, I've tested the upgraded code by running the test app in this repo, as well as by referencing it in my actual target project, and both seem to work fine.
