### ISSUE TITLE
Features: Open event, Close event

### ISSUE THREAD

**Issue by vincecampanale** [zefoy/ngx-color-picker#30]
A great addition to this widget would be the ability to hook into open and close events for the widget. This would make certain things a lot easier.

Feature: Open Event
Use case: Lock everything on the page when the user opens the color picker. (So they don't click out and accidentally trigger another action.)

Feature: Close Event
Use case: Rather than sending an update event to the server every time the color changes (and having to debounce it inside the handler function or something), just dispatch a save when the user closes the picker.

**Comment by vincecampanale** [comment]
I'd be happy to work on this, let me know if you think it's worthwhile.

**Comment by sconix** [comment]
Yes this would make sense and is easy to implement. PR is more than welcome still since currently I am bit short on time :)

**Comment by sconix** [comment]
I will add these events for the next release.

**Comment by sconix** [comment]
I just realized that there is a cpToggleChange event emitted with value true / false depending if the dialog is open.
