### ISSUE TITLE
Multiple color pickers are being affected at the same time

### ISSUE THREAD

**Issue by nahuelleiva** [zefoy/ngx-color-picker#305]
Hi, first and foremost I found this plugin really helpful for what I'm looking for.

I found that using multiple inputs like the docs say they should be used, once I start working with one the other ones get affected as well, even if I use a different id on each one.

Docs suggest that the component should be used like this:
`<input [(colorPicker)]="color"
                            [style.background]="color"/>`
but if I do something like this:
`<div><input [(colorPicker)]="color"
                            [style.background]="color" id="primary"/> <input [(colorPicker)]="color"
                            [style.background]="color" id="secondary"/></div>`
and then I proceed to use "primary", "secondary" also gets affected if I change the color on "primary".

Maybe is a dumb question and I'm not seeing the error, but what should I do in this case?

**Comment by ntrannghia** [comment]
it should be
<input [(colorPicker)]="color1" [style.background]="color1" id="primary"/>
<input [(colorPicker)]="color2" [style.background]="color2" id="secondary"/>
