### ISSUE TITLE
Not working on standalone components

### ISSUE THREAD

**Issue by Sergiobop** [zefoy/ngx-color-picker#316]
Hi!

The package does not work if imported in a standalone component:

```
vendor.js:14415 NullInjectorError: R3InjectorError(Standalone[...])[ColorPickerService -> ColorPickerService -> ColorPickerService -> ColorPickerService -> ColorPickerService]: 
  NullInjectorError: No provider for ColorPickerService!
```

I had to use a module to make it work

**Comment by alinmateut** [comment]
For me works except when I use the directive inside standalone Angular Material's dialogs

**Comment by DDtMM** [comment]
The issue here is how the service is provided.  Instead of providing it as part of the module, if the ColorPickerService's annotations where changed to use `{ providedIn: 'root' }` then the issue should go away.

**Comment by Benny739** [comment]
> The issue here is how the service is provided. Instead of providing ColorPickerService as part of the module, if the annotations where changed to use to provide in root then the issue should go away.
> 
> My only hesitation to just creating a PR is if there was a design reason to providing the service this way. _I think_ as it is today, if the module was imported into two sub modules then that would allow multiple color pickers to be visible as once. So changing the program as I suggest could break some functionality.

I think this would be a good change, currently we can not lazy load the color picker and need to to import it in the root module.

**Comment by tiberiuzuld** [comment]
Hello,
Adding `viewContainerRef` to dialog fixes the issue:
```ts
    this.dialog
      .open(MyDialogComponent, {viewContainerRef: this.viewContainerRef})
```
