### ISSUE TITLE
This application depends upon a library published using Angular version 14.2.3, which requires Angular version 14.0.0 or newer to work correctly

### ISSUE THREAD

**Issue by legenddaniel** [zefoy/ngx-color-picker#317]
I am using Angular 13.0.3 and I got error when using `ColorPickerModule` and run `ng serve`:

./node_modules/ngx-color-picker/fesm2020/ngx-color-picker.mjs - Error: Module build failed (from ./node_modules/@angular-devkit/build-angular/src/babel/webpack-loader.js):
TypeError: Cannot create property 'message' on string 'D:\some_path\app\node_modules\ngx-color-picker\fesm2020\ngx-color-picker.mjs: This application depends upon a library published using Angular version 14.2.3, which requires Angular version 14.0.0 or newer to work correctly.

> 128 | TextDirective.ɵdir = i0.ɵɵngDeclareDirective({ **minVersion: "14.0.0"**, version: "14.2.3", type: TextDirective, selector: "[text]", inputs: { rg: "rg", text: "text" }, outputs: { newValue: "newValue" }, host: { listeners: { "input": "inputChange($event)" } }, ngImport: i0 });

    at run (D:\some_path\app\node_modules\@babel\core\lib\transformation\index.js:37:15)
    at run.next (<anonymous>)
    at Function.transform (D:\some_path\app\node_modules\@babel\core\lib\transform.js:25:41)
    at transform.next (<anonymous>)
    at step (D:\some_path\app\node_modules\gensync\index.js:261:32)
    at D:\some_path\app\node_modules\gensync\index.js:273:13
    at async.call.result.err.err (D:\some_path\app\node_modules\gensync\index.js:223:11)
    at D:\some_path\app\node_modules\gensync\index.js:37:40

Is it compatible with Angular 13? Or I must upgrade to Angular 14 to use it?

**Comment by sconix** [comment]
You can use older version with Angular 13.
