### ISSUE TITLE
HUE Slider bug

### ISSUE THREAD

**Issue by DanielKucal** [zefoy/ngx-color-picker#33]
I don't have a default color, it should be undefined till user defines one. But then initial value for `[(colorPicker)]` is undefined, then occurs a bug with not working HUE slider visible on the video: https://youtu.be/kDj2qYQazNk

**Comment by sconix** [comment]
I will check this tomorrow, in the mean time you can always pass in some default color or empty string when value is undefined and it should work as a simple workaround.

**Comment by sconix** [comment]
This will be fixed in the next release.
