### ISSUE TITLE
dialog position is not correct in latest upgrade 14.x

### ISSUE THREAD

**Issue by sumegha26** [zefoy/ngx-color-picker#331]
Before 14.x upgrade - `ngx-color-picker: 13.x` 

![After_ugrade](https://user-images.githubusercontent.com/16117586/221778650-86bc93d0-8282-4c64-a023-b3f087fdad66.PNG)

After 14.x upgrade - `ngx-color-picker: 14.x` 

![Before_upgrade](https://user-images.githubusercontent.com/16117586/221778593-e043ed83-ff0e-49b3-b38b-0cf3b9fec3e4.PNG)

**Comment by bjornharvold** [comment]
Yes. Experiencing this too. Had to move from "auto" to "top".

**Comment by orestisioakeimidis** [comment]
+1 here, I have the same issue.

**Comment by REPTILEHAUS** [comment]
+1 same issue

**Comment by alecarn** [comment]
Same issue for us, since v14 the position is incorrect

**Comment by MelanieW97** [comment]
+1
I have just downgraded to v13 and it's working. Definitely a bug in v14.

**Comment by MelanieW97** [comment]
It's still not working for me in version 15 in all cases. I still have to use version 13.
https://github.com/zefoy/ngx-color-picker/issues/338#issuecomment-1728887637
