### ISSUE TITLE
Feature request. (onClose) event to emit value

### ISSUE THREAD

**Issue by JakobSegerslatt** [zefoy/ngx-color-picker#35]
It would be really helpful if the directive could add an onClose event which fires the value when the user clicks outside the popup and thus closes it. This is different from explicitly canceling the operation (clicking the cancel button) in my opinion. 
`
@Output('onClose') onClose = new EventEmitter<string>();
`
It's a nice callback to have.

**Comment by sconix** [comment]
There is a cpToggleChange event which tells the open/close state of the color picker.

**Comment by JakobSegerslatt** [comment]
That works nicely, should have noticed that one.
