### ISSUE TITLE
Compatibility issue with mdSelect

### ISSUE THREAD

**Issue by lukaszkostrzewa** [zefoy/ngx-color-picker#36]
I tried to use ngx-color-picker with Select from Angular Material Design library and I encountered some issue. 

When you open a select there is an error in the console:
`TypeError: Cannot read property 'setFirstItemActive' of undefined`

and it's impossible to select an option. It seems like `_keyManager` is not being initialized when mdSelect is used with ngx-color-picker. Without ngx-color-picker it works of course. However, I'm not sure where the problem lies – maybe it's not on the ngx-color-picker side, but I think it will be good to further investigate the issue. 

Here's a Plunker with the problem recreated: http://plnkr.co/edit/YPMhTnVP1TV3K89EwfrP?p=preview.

**Comment by sconix** [comment]
How can I reproduce the error? If I try the Plunker it works and I don't get any errors.

**Comment by lukaszkostrzewa** [comment]
With v4.0.3 (I updated the version in the Plunker) just open the select. However, it looks like it's been already fixed in v4.1.0 :)

Yesterday I opened the ticket and now it's already fixed – you are so fast! :+1:

**Comment by sconix** [comment]
I did some position related changes and removed the initial change event so maybe those fixed this issue as well :)
