### ISSUE TITLE
IE10 - Colorpicker does not close

### ISSUE THREAD

**Issue by sumedh-coditas** [zefoy/ngx-color-picker#44]
The Color picker does not close when clicked outside of the color-picker or using the "OK" or "Cancel" button in IE10.
Also, the UI is not as it seems in other browsers.

**Comment by sconix** [comment]
Well the common trend is to not support IE10 so I am not that interested about supporting EOL browsers. I can look into it at some point that if its a quick fix or somebody provides a PR.

**Comment by sumedh-coditas** [comment]
Appreciate your quick reply.
And yes, if you could look into this IE10 support for a quick fix, it would help us a lot. 
Also, if I get some time, I might provide you a PR myself.
Thanks...! :)

**Comment by sumedh-coditas** [comment]
@sconix I believe, the issue is due to [hidden] attribute used on HTML elements.
check this (https://github.com/angular/angular/issues/5774)

**Comment by sconix** [comment]
Thanks, I will have a quick look next week. If its not quick fix then I will wait for PR. Since we are not supporting IE10 even in our company apps, hence my interest to this is sadly not so high.

**Comment by sumedh-coditas** [comment]
@sconix I have created PR for IE10 support
https://github.com/zefoy/ngx-color-picker/pull/45

**Comment by sconix** [comment]
Thanks, I will check it and merge. Will then release a new version (at the latest tomorrow).

**Comment by sumedh-coditas** [comment]
@sconix any update on this?

**Comment by sconix** [comment]
I will do a new release later today.

**Comment by sumedh-coditas** [comment]
Ok.. thanks!!

**Comment by sconix** [comment]
I am really busy atm, trying to get next release out of our product out so there is a small change that this still has to wait until tomorrow,. So tomorrow I can make the new release for sure, but I try to make it already today.

**Comment by sumedh-coditas** [comment]
It's all good.. I will wait for your next release but try to make it ASAP.

**Comment by sconix** [comment]
I just release the new version with the IE10 fixes merged. Let me know if there are other fixes needed for IE10.

**Comment by sumedh-coditas** [comment]
@sconix Thanks.. i will test and let you know if there are any issues.
