### ISSUE TITLE
Append to <body> tag 

### ISSUE THREAD

**Issue by baonguyenyam** [zefoy/ngx-color-picker#47]
Hi all!

I saw the picker alway append after the input tag, how about if i want append it to the body tag?

Thanks!

**Comment by sconix** [comment]
There is a option called 'cpUseRootViewContainer' which can be used to make the color picker create the dialog component in the application root which usually is the body. If you set it to true you must also expose the view container in your root component by having: 'public viewContainerRef: ViewContainerRef' in your root components constructor.

**Comment by thienthuatnguyen** [comment]
Can you give me example code when use [cpUseRootViewContainer] = "true" with  ViewContainerRef
