### ISSUE TITLE
Overriding CSS

### ISSUE THREAD

**Issue by donmckenna** [zefoy/ngx-color-picker#49]
This may be a dumb / obvious question, but how would I go about overriding some simple css styles?
I can't seem to target .color-picker / child elements with css/scss.
Not sure if I'm trying to target the elements incorrectly, or if it isn't possible in this way.
Any clarification would be appreciated.

**Comment by sconix** [comment]
There is nothing library specific in overriding styles. So you need to look into Angular and how to style components. It requires usage of /deep/ selector if you are using ViewEncapsulation.

**Comment by donmckenna** [comment]
Thanks for the reply, playing around with /deep/ I was able to target .color-picker successfully.
I'm aware of how to style Angular components and the /deep/ selector, but I thought /deep/ was deprecated, which is why I was hesitant in using it.

**Comment by sconix** [comment]
I have understood that its only deprecated if you are using native or any other than the default view encapsulation. The documentation is bit unclear about what actually which support will be dropped. At least I am not aware of any other way to style the components when using the view encapsulation so not sure what should be used if that means that the support is also removed from the emulated view encapsulation.
