### ISSUE TITLE
OutPutFormat field is not working properly

### ISSUE THREAD

**Issue by Sathishchary** [zefoy/ngx-color-picker#53]
I have added the out put format as 'hex' but its showing all HEX and HSLA and RGBA in the color picker popup box. How can i show only hex in the popup.  I am seeing below code in demo wiki. there is option like

Options	Values (default values in bold)
`  cpOutputFormat	'hex', 'rgba', 'hsla' // here hex is default`

html: 
```
<div>
	<input [(colorPicker)]="playerColorPicker"  [value]="playerColorPicker"
	   (colorPickerChange)="changePlayerColor($event)" [cpOutputFormat]="'hex'"  
          [cpWidth]="'200px'" [cpHeight]="'265px'" />
</div>
```

is there any way to hide the hsla and rgba in popup window.?

thanks

**Comment by sconix** [comment]
Why would yo want to hide them? Isn't it important that user can input the color as he knows the color. The output format just makes sure that you always get the color in the wanted format.

Naturally you can always use CSS to hide the components from the dialog, but at the moment there are no options for hiding components in the dialog.

At some point I am making a cleanup / re-factoring when one can even make totally custom dialog easily and leave out the none wanted elements but there is no timeframe for this.
