### ISSUE TITLE
TypeError: Cannot set property 's' of undefined

### ISSUE THREAD

**Issue by errorx666** [zefoy/ngx-color-picker#54]
ColorPickerComponent.html:1 ERROR TypeError: Cannot set property 's' of undefined
    at ColorPickerComponent.setSaturationAndBrightness (color-picker.component.js:305)
    at Object.eval [as handleEvent] (ColorPickerComponent.html:1)
    at handleEvent (core.es5.js:12022)
    at callWithDebugContext (core.es5.js:13486)
    at Object.debugHandleEvent [as handleEvent] (core.es5.js:13074)
    at dispatchEvent (core.es5.js:8615)
    at core.es5.js:10783
    at SafeSubscriber.schedulerFn [as _next] (core.es5.js:3647)
    at SafeSubscriber.__tryOrUnsub (Subscriber.js:238)
    at SafeSubscriber.next (Subscriber.js:185)
View_ColorPickerComponent_0 @ ColorPickerComponent.html:1
proxyClass @ compiler.es5.js:15129
DebugContext_.logError @ core.es5.js:13426
ErrorHandler.handleError @ core.es5.js:1080
(anonymous) @ core.es5.js:10787
schedulerFn @ core.es5.js:3647
SafeSubscriber.__tryOrUnsub @ Subscriber.js:238
SafeSubscriber.next @ Subscriber.js:185
Subscriber._next @ Subscriber.js:125
Subscriber.next @ Subscriber.js:89
Subject.next @ Subject.js:55
EventEmitter.emit @ core.es5.js:3621
SliderDirective.setCursor @ helpers.js:58
SliderDirective.start @ helpers.js:66
(anonymous) @ ColorPickerComponent.html:1
handleEvent @ core.es5.js:12022
callWithDebugContext @ core.es5.js:13486
debugHandleEvent @ core.es5.js:13074
dispatchEvent @ core.es5.js:8615
(anonymous) @ core.es5.js:9226
(anonymous) @ platform-browser.es5.js:2651
ZoneDelegate.invokeTask @ zone.js:425
Zone.runTask @ zone.js:192
ZoneTask.invokeTask @ zone.js:499
invokeTask @ zone.js:1427
globalZoneAwareCallback @ zone.js:1445

![image](https://user-images.githubusercontent.com/1048542/30405100-a18d3aba-98af-11e7-896f-2e925cdc77a6.png)

**Comment by errorx666** [comment]
I'm not sure what I changed but I got it working.

**Comment by errorx666** [comment]
This works when I edit some items but not others, and I'm not sure what's different between them.  They all share the same template.

**Comment by errorx666** [comment]
Notice also that the dialog is far below where it should be.  It only gets positioned if I blur and re-focus the input.  It appears that the first time, setDialog gets called but openDialog does not, and openDialog performs the positioning.

**Comment by errorx666** [comment]
More debugging...  The working item hits a breakpoint in ColorPickerComponent.ngOnInit, but the non-working item seems to skip ngOnInit.

**Comment by errorx666** [comment]
I figured it out.  I had an ancestor view that was making changes outside of its zone.  Using zone.run resolved my issue.

**Comment by mmakhalaf** [comment]
@errorx666 I understand this is probably not the place for this, but I have exactly the same problem as you had, but not the same level of experience :) . Could you please elaborate on what you had to do with the zones to fix this? I'm suspecting it's the same thing because when putting the <input..> in the top level component, it works, but in my sub-component (which is inside a module run through a named outlet) doesn't. Thanks

**Comment by errorx666** [comment]
@mmakhalaf 

To solve the problem, you need to add to your component or service's constructor the dependency `NgZone` from `@angular/core`, and save a reference as `this.zone`.

Then, whenever you need to mutate the state of your component, wrap it in `this.zone.run`.

If you're doing it from an rxjs `Observable` subscription, then I'll take this opportunity to plug an Angular module I wrote to solve exactly this problem: https://npmjs.com/package/ngx-zone-scheduler

To use it, import `ZoneSchedulerModule` into your app module, and `@Inject(ZoneScheduler) scheduler: SchedulerLike` to your component.  Then, before you subscribe, call `observeOn( this.scheduler )`.  Then you don't need to worry about calling `zone.run`.

**Comment by mmakhalaf** [comment]
@errorx666 Thank you for taking the time to explain this
