### ISSUE TITLE
Disable simplification of hex colors

### ISSUE THREAD

**Issue by Pikachews** [zefoy/ngx-color-picker#57]
Could an option be added to disable simplifying hex colors? e.g. disable #FFFFFF -> #FFF

**Comment by sconix** [comment]
I have planned to remove the simplifying since imho its not very useful, but since this is something that is very easy to have a workaround I decided to let this wait until I do the bigger cleanup for this library.

**Comment by sconix** [comment]
I decided to disable the simplification already for 4.4.0 release. Lets see is it causes problems for anybody.
