### ISSUE TITLE
Failed to load color-picker.component.html

### ISSUE THREAD

**Issue by Pikachews** [zefoy/ngx-color-picker#58]
I downloaded the repository, and built it using `npm run build` without making any modifications.
When I replaced the files in my project (which is using ngx-color-picker) with the files I built, loading any component containing a color picker gives me the following errors:

```
GET http://localhost:4200/color-picker.component.html 404 (Not Found)
ERROR Error: Uncaught (in promise): Failed to load color-picker.component.html
```

When I compared the two, I see that there is one main difference, the files that were downloaded from npm inlined the template and css, whereas the ones I built did not inline them (they still contained: `templateUrl: './color-picker.component.html'` and the same for the css).

Am I missing a step when building the project?

**Comment by Pikachews** [comment]
I completely missed the `npm run inline` but that still did not seem to inline the files.

**Comment by sconix** [comment]
It depends on the command shell how it interprets the quotes. I don't see a problem with this change so I will merge it after the weekend.
