### ISSUE TITLE
how to add validation to the color picker

### ISSUE THREAD

**Issue by andrewsafwat** [zefoy/ngx-color-picker#60]
i want to add a validation like required validator and a custom validator to validate if this color used before or not
`<input [(colorPicker)]="addingNewThreshold.color" class="color-input" [formControlName]="'addColor'" [cpOutputFormat]="'hex'"
                                        [style.background]="addingNewThreshold.color" readonly [cpCancelButton]="true" [cpCancelButtonClass]="'btn btn-primary btn-xs'"
                                        [cpSaveClickOutside]="false" [cpOKButtonClass]="'btn btn-primary btn-xs'" [cpOKButton]="true"/>`

`validateColorExists(c: any, thresholds, threshold: any = null) {
        let result = thresholds.filter(t => t.color == c.value && t != threshold);
        return result.length == 0 ? null : {
            validateColorExists: {
                valid: false,
                fieldLength: 'This color already exists'
            }
        };
    }`

but c.value always will be empty as i don't use the value attribute, what should i do

**Comment by ekstremedia** [comment]
@andrewsafwat this works: 
            <input [(colorPicker)]="color"  **(colorPickerChange)="editEvent.get('color').setValue($event)"** [cpOKButton]="true" [style.background]="color" cpOutputFormat="hex" cpFallbackColor="#ccc" cpAlphaChannel="false" />
Where editEvent is my formgroup, and color is the this.color in that formgroup.
