### ISSUE TITLE
ReferenceError: navigator is not defined

### ISSUE THREAD

**Issue by kudsyf** [zefoy/ngx-color-picker#61]
am getting this error ( with Angular 4.3.1 , Angular-cli)

/Users/CodeBase/app/node_modules/ngx-color-picker/dist/lib/helpers.js:131
var ua = navigator.userAgent.toLowerCase();
                             ^

ReferenceError: navigator is not defined

any idea how to fix this one ?

**Comment by robmeredith** [comment]
same issue when running on Universal

**Comment by sconix** [comment]
The IE10 detector seems to be buggy, I will release a fix on Monday so that it won't error out if navigator is not available.
