### ISSUE TITLE
Error: ViewDestroyedError: Attempt to use a destroyed view: detectChanges

### ISSUE THREAD

**Issue by meiuqer** [zefoy/ngx-color-picker#63]
I'm working with this colorpicker and i have the [cpSaveClickOutside] set to false. So when i click outside it changes back to the initial value.
This works like intended but when i click somewhere in my app that removes the colorpicker (i.e. changes the view to somewhere else in the app) it gives me this error:

> Error: ViewDestroyedError: Attempt to use a destroyed view: detectChanges

If i go look for the detectChanges, i can found a detectChanges call here:

`    ColorPickerComponent.prototype.closeColorPicker = function () {
        if (this.show) {
            this.show = false;
            this.directiveInstance.toggle(false);
            document.removeEventListener('mousedown', this.listenerMouseDown);
            window.removeEventListener('resize', this.listenerResize);
            this.cdr.detectChanges();
        }
    };
`

in the 

> color-picker.compontent.js

taken from the google dev tools.

Is this working as intended? Shouldn't there be some kind of check or something? Please correct me if i'm wrong.

**Comment by sconix** [comment]
Looks like faulty code, will fix for todays release. Thanks for reporting this and please let me know if it wont work with the new version.

**Comment by meiuqer** [comment]
Thanks, will let you know how it works!

**Comment by sconix** [comment]
But the color is already resetted with the mousedown event not in the close function. So the close function is called after the color has been set back to the initial color.  I wonder if your app destroyes the color picker before it has change to send the color changed event. Since from the code I can't see anything that could cause problems

**Comment by sconix** [comment]
Can you try and add some logging to cpToggleChange and colorPickerChange events and see if either of those fire when you click outside.

**Comment by meiuqer** [comment]
>  I wonder if your app destroyes the color picker before it has change to send the color changed event.

This is probably the case. Consider this use case, which resembles mine:

I have a dropdown menu with the colorpicker in it. If i click outside the colorpicker but inside the dropdown menu, the colorpicker closes and dropdown menu stays open. BUT if i click outside the color picker and outside the dropdown menu, they both close and my guess is the dropdown menu closes first, so the color picker is already destroyed.

> Can you try and add some logging to cpToggleChange and colorPickerChange events and see if either of those fire when you click outside.

I will do this tomorrow when im back at work.

**Comment by meiuqer** [comment]
I just added some logging. These two don't get logged when i click outside the dropdown and outside the color picker.

**Comment by sconix** [comment]
Ok so then I guess that color picker is destroyed before those output emits are handled. The other one is send on mousedown and the other in the close function that you got the error earlier. One of those outputs is async and other is not so that why I wanted you to test both.

So I am not sure if there is anything I can do in the color picker to fix your problem, I think the only thing you can do is to somehow change the order / way the components are destroyed. Since color picker can't capture the outside click event since that would cause problems for sure. If you have some ideas how to handle this is color picker I would love to hear. 

How it is now that color picker listens on mousedown event and if cpSaveClickOutside is false then it emits the colorPickerChange event (not async) with the reverted color and then calls close color picker function which emits the cpToggleChange (async) event. So the color reverting is done in the earliest phase possible.

**Comment by meiuqer** [comment]
Okay, i'll start looking for a solution in my app. Probably rearranging the order that the components gets destroyed would be a good solution indeed. Thanks for thinking with me.

I've also been digging through the color picker code, but couldn't find a solution for the problem at first sight. If I happen to find one, i'll let u know. Because i think the use case i described is a problem more people can encounter.

**Comment by sconix** [comment]
Yes it would be nice to be able to solve this in the library, but I am out of ideas. Keep me posted if you get some ideas.

**Comment by meiuqer** [comment]
Solution that applies to my app:

I have your colorpicker directive attached to a div in my own colorpicker component. In the component's onDestroy i emit the initialColor, only when it's defined. This seems to work in my case.

     ngOnDestroy() {
        if (this.initialColor !== undefined) {
            this.colorChange.emit(this.initialColor);
        }
    }

Don't know if this can be useful to some, but in my case it looks like it's fixed.

**Comment by jmaicaaan** [comment]
+1 encountering this one also.

**Comment by meiuqer** [comment]
If you are encountering this problem, you'll have to do stuff inside ngOnDestroy(). This will depend on what kinda stuff you want to do with the colorpicker but normally you can make it work.

**Comment by jmaicaaan** [comment]
My scenario is that I have the color picker inside the mdDialog (angular material), and then when the user escapes or pressed the `esc button` then re-open again the mdDialog it throws that error. For the reason that the color-picker is still *open* when the mdDialog was closed.

My approach I've made to band-aid it was to trigger the cancel button in the color picker by getting the element upon beforeClosing event of the mdDialog. 

What are your thoughts on that? I don't think it is a good one though

**Comment by jmaicaaan** [comment]
Issue demo: https://angular-material2-issue-jncwfq.stackblitz.io/
Click button then press escape to close the dialog without closing the color-picker popup

**Comment by meiuqer** [comment]
you should check if you have the most recent version of this library, first of all. normally there's a fix for this issue. but it could be possible that you encounter other issues with it.

**Comment by jmaicaaan** [comment]
@meiuqer, it was the latest version. Have you seen my demo?

**Comment by meiuqer** [comment]
Yes, normally this error was fixed. If u still get this error its probably
something else. Ill have to check tomorrow again.

**Comment by jmaicaaan** [comment]
Thanks for the help @meiuqer! Will further check it out.
