### ISSUE TITLE
ERROR during build Webpack AOT

### ISSUE THREAD

**Issue by ClaudioKirchmair** [zefoy/ngx-color-picker#65]
The error occurs when I add "import { ColorPickerModule } from 'ngx-color-picker';" to my module.

ERROR in ./node_modules/ngx-color-picker/dist/lib/color-picker.component.css
    Module build failed: Error: "extract-text-webpack-plugin" loader is used without the corresponding plugin, refer to https://github.com/webpack/extract-text-webpack-plugin for the usage example
        at Object.pitch (...)

Stuff from my webpack configs:

> const ExtractTextPlugin   = require('extract-text-webpack-plugin');
>
>  module: {
    rules: [
      ...
      {
        test: /\.css$/,
        include: helpers.root('./src/style.css'),
        use: ['style-loader', 'postcss-loader']
      },
      {
        test: /\.css$/,
        exclude: helpers.root('./src/style.css'),
        use:  ExtractTextPlugin.extract({fallback: 'style-loader', use: 'css-loader'})
      },
    ]
  },
  ...
  plugins: [
    ...
    new ExtractTextPlugin('[name].[hash].css'),
    ...
  ]

Any guess how to solve it?

**Comment by ClaudioKirchmair** [comment]
I think has to do something with the fact that I'm using *.scss files in my Angular Components and therefore the stylesheet loader isnt't configured right for Angular Components *.css files.

**Comment by sconix** [comment]
I am not a Webpack expert so can't help much, but if you are right then don't you just need to add the css file to the exclude list.

**Comment by dbettini** [comment]
Had the same problem, using .scss for component styles and getting all .css files extracted with ExtractTextPlugin into a separate css file. Fixed it by making an exclusive rule for ngx-color-picker css, so it gets inlined where it's required instead:
```
{
  test: /\.css$/,
  exclude: /ngx-color-picker/,
  use: ExtractTextPlugin.extract({
    fallback: "style-loader",
    use: "css-loader",
  }),
},
{
  test: /\.css$/,
  include: /ngx-color-picker/,
  use: ["to-string-loader", "css-loader"],
},
```

In my opinion, this should not happen. ngx-color-picker should probably inline that css into the component.js in the build step, or expose the library as a typescript source.

**Comment by sconix** [comment]
The css file is inlined in the js and nothing is referencing to it so thats why I believe that the fault is in the webpack configuration, but not sure since I am not that familiar with Webpack. All I know that angular-cli plays nice so there is a webpack configuration that works very well for this library.

**Comment by dbettini** [comment]
@sconix it works because angular-cli doesn't use ExtractTextWebpackPlugin. Not everyone should or will use their configuration. It seems this library isn't compatible with configs that bundle css using the plugin while using scss for component styles.

**Comment by sconix** [comment]
Yes, but I still believe that the problem is the webpack configuration not the library. Since the library does not ask to include the css file so its the webpack configuration that pulls it in afaik. I could leave out the css file, but at least other libs which inline the css will still ship with the css file so I am doing the same.

**Comment by dbettini** [comment]
Webpack should not be including it if it's inlined in the js (that is, not required anywhere), so not sure what's happening there. It works in JIT, seems like something that AOT loader does creates a problem

**Comment by sconix** [comment]
Actually I found out that the metadata.json did not have templates inlined so that might have been causing issues with some build system. From 5.0.0 onwards this has been fixed so that templates are inlined in metadata.json as well.
