### ISSUE TITLE
I am not able to change the color of text inside color picker

### ISSUE THREAD

**Issue by nidhiguptm** [zefoy/ngx-color-picker#67]
I am not able to change the text color inside color picker. by default it is showing white in color so i am not able to see hex code of the color.

![image](https://user-images.githubusercontent.com/32539877/31221954-01895f72-a9e3-11e7-8318-5cf64a65909b.png)

**Comment by sconix** [comment]
Normal angular styling rules apply. Some style you have is effecting the color picker since the default color of the text is not white. So either fix that style which is effecting it or just override it.
