### ISSUE TITLE
Display issues when [cpDialogDisplay]="inline"

### ISSUE THREAD

**Issue by spfuller** [zefoy/ngx-color-picker#68]
When [cpDialogDisplay]="inline" the color-picker class is positioned absolute. This causes the color picker to appear over the top of any elements that may be below it. So it seems to still be acting like a popup. It would be nice if elements below wrapped nicely around the color picker instead of appearing behind it.

![image](https://user-images.githubusercontent.com/32622986/31321524-3f2b6d64-acd3-11e7-919e-4f13082f0517.png)

**Comment by sconix** [comment]
That a bug, will fix for next release which I will do this week.

**Comment by sconix** [comment]
This should be now fixed in the 4.3.5 release which I just made.
