### ISSUE TITLE
Edit color value before opening the color picker

### ISSUE THREAD

**Issue by RobArbor** [zefoy/ngx-color-picker#69]
Hello this issue can be reproduced using the demo page.

Steps to reproduce:
1.  Select text with keyboard only or by selecting the text and have the 'mouse up' outside the textbox.
2.  Enter a color

Notice that the color of the textbox wont change any more. Errors are displayed in the javascript console.
Can be restored by clicking on the textbox so that the color picker opens.

![image](https://user-images.githubusercontent.com/18066581/31388808-833b545e-adcf-11e7-987e-a0aac6a3a2c5.png)

I think the issue is that the color picker component is not created when using for example the keyboard navigation. Is it possible to open the color picker using the onFocus event instead of the onClick event?

**Comment by sconix** [comment]
Thanks for the report, I was able to reproduce the error. Will release a fix tomorrow.

**Comment by sconix** [comment]
This is now fixed in 4.3.6.
