### ISSUE TITLE
How to get color code in textbox ?

### ISSUE THREAD

**Issue by lakinmohapatra** [zefoy/ngx-color-picker#71]
I used this plugin .
Once i select the color , its showing it inside  input box. 
But its color code is not set inside input box. 
How to get it ?

**Comment by sconix** [comment]
Not sure what you mean, but the example app has plenty of examples.

**Comment by wartab** [comment]
You need to use two-way databinding for that as shown in the example of the main page of this repo.

**Comment by lakinmohapatra** [comment]
see, i am using formcontrol name . So formcontrol name should contain its color.
But its not.

**Comment by wartab** [comment]
Without an example, we will have a hard time helping you out.

**Comment by b-r-s** [comment]
<input class="editorSelectOption" [(colorPicker)]="colorPickerColor" [style.background]="colorPickerColor" **[value]="colorPickerColor"**
        id="clr_picker" [cpOKButton]="true" [cpCancelButton]="true" (colorPickerChange)="colorChanged($event)" (colorPickerSelect)="colorSelected($event)"
      />
In your html to setup the colorpicker (see my example above) add the option "[value]="TheVariableYouAreUsingToTrackTheCurrentColor" -- in my case I have called it "colorPickerColor".  This will set the entry field to the value of the current color.

**Comment by lakinmohapatra** [comment]
Thanks a lot . I will try and update here

**Comment by b-r-s** [comment]
:)  - happy to assist - please let me know if this dose not work for you - and attach your html for setting up your color picker.
  
 b
  
  
  

----------------------------------------
