### ISSUE TITLE
Cannot read property 'a' of undefined 

### ISSUE THREAD

**Issue by vistajess** [zefoy/ngx-color-picker#80]
Sometimes it works fine, but sometimes it doesnt due to this issue.

What seems to be a problem on this case??

![image](https://user-images.githubusercontent.com/12708502/32798393-83dd7652-c9af-11e7-81b1-8dfbbb6b1de3.png)

here's my code: 

![image](https://user-images.githubusercontent.com/12708502/32798420-981cf548-c9af-11e7-8cea-284c3cec048d.png)

Suggestions will be highly appreciated.

**Comment by sconix** [comment]
Can the baseColors.sub sometimes be invalid color value? Hard to say without way to reproduce the error.

**Comment by vistajess** [comment]
I found a mistake on my end. Sorry. 
Now its working perfectly :) 

Thanks , I will close this issue.

**Comment by sconix** [comment]
If you can elaborate what the mistake was I would like to add a check that such thing can't cause an error :)

**Comment by vistajess** [comment]
Okay here's the scenario, I am building a color scheme feature for a dynamic web app. I am using MEAN stack.
Currently, I have model for base colors  `baseColors = { main: null, sub: null }`. The adding of colors to the database was fine and I noticed that somewhere in my code that I am not including the `sub` color  in my payload (AJAX) when updating.
