### ISSUE TITLE
flashes when it pops up.

### ISSUE THREAD

**Issue by shanks-devil** [zefoy/ngx-color-picker#81]
hi
sometimes,the dialog  flashes when it pops up.
您好
有时，对话框在弹出时会闪一下。
 ```
// ColorPickerComponent
setTimeout(function () {
                _this.setDialogPosition();
                _this.hidden = false;
                _this.cdr.detectChanges();
}, 0); 
```
I changed the timeout's time from 0 to 100 , and it's woking well now.

**Comment by sconix** [comment]
I haven't noticed any flashes and don't quite understand how making timeout longer would reduce flashing, but looking at the code there is something weird in that piece of code that might cause the problem with certain situations. I will include a small fix for next release which should fix this.
