### ISSUE TITLE
cpToggleChange execute event true false true every time

### ISSUE THREAD

**Issue by malecki-se** [zefoy/ngx-color-picker#82]
When click to input and check state with method `cpToggleChange` every time get true false and true. So probably color picker is open close and open, really fast but sometimes shuttering is seen.

Version of color-picker 4.5
View:
`<input [(colorPicker)]="color" (cpToggleChange)="onToggleChange($event)" />`

Component:
```
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  color: '#dddfff';

  constructor() { }

  onToggleChange(event) {
    console.log(event);
  }

}
```

**Comment by sconix** [comment]
I am actually looking to this as soon as I have time, this was reported in other issue as well, but this gives more info to me so thanks.
