### ISSUE TITLE
Wrong file imported .css

### ISSUE THREAD

**Issue by dsubale** [zefoy/ngx-color-picker#86]
Hi,
When I install ngx-color-picker in my project with npm install.
It will create installed with no error but when I do ng build error is occurred.
The error is  Wrong file imported in ngx-colorpicker/src/lib/colorpicker.component.ts
@Component({
    selector: 'colorpicker',
    templateUrl: './colorpicker.component.html',
    styleUrls: ['.**/colorpicker.component.css'**]  ///**Here we are importing .css file but there no css file present in same directory, there is .scss file present** 
})

Every time I have to modify the colorpicker.component.ts file making .css to .scss.
Please fix this so that every one can have updated code.

**Comment by sconix** [comment]
Problem is in your build system. And where do you even get that file the src directory is not shipped with the npm package. Are you using git as the package? If you are using source then its your job to build the library.
