### ISSUE TITLE
Add color submits the form

### ISSUE THREAD

**Issue by itafraji** [zefoy/ngx-color-picker#87]
If you use it inside a form with other controls, button add color submits the form.

**Comment by itafraji** [comment]
My current solution is to wrap picker in another form.

**Comment by sconix** [comment]
It seems that the event handler is missing stop propagation so most likely you have a click event handler that catches the button click. So you can also fix it by just checking that the click comes from the button you are expecting it to come. Anyway I will fix this for next release.
