### ISSUE TITLE
ionic 2/3 with angular 4 -- not getting color selection pop up

### ISSUE THREAD

**Issue by dx1096** [zefoy/ngx-color-picker#9]
I am using this library with ionic2/3 app and angular 4.

I am not getting color selector pop up box when input box is clicked. 

However, changing color code in input box changes the color.

I did not see any error in console logs. I tried it in chrome browser.

Any clue?

**Comment by sconix** [comment]
I am not familiar with Ionic so can't say, but I think I have heard people using this in such projects. If you can pinpoint the exact problem then I can look into this, but until somebody gives more info there is not much I can do.

**Comment by dx1096** [comment]
Yes, I understand. I saw couple of tickets( #4 and #7 ) with ionic 2/3 reference which are now closed.
I avoided commenting on closed tickets hence opened a new one. 

If you are okay, should i comment on closed ticket, so as to get some help?

**Comment by sconix** [comment]
Sure you can try commenting on closed tickets to try and see if you can reach the reporters and get some help.

**Comment by super-iterator** [comment]
@dx1096 Have you found a solution to the color picker on ionic 2?

**Comment by lscarneiro** [comment]
For those whom were/are suffering with this component to work with Ionic, try playing with the cpDialogDisplay setting, it really looked not working for me until I tried cpDialogDisplay="inline", and then, BOOM! It worked!
