### ISSUE TITLE
cpDisableInput not hiding arrows

### ISSUE THREAD

**Issue by VincentG85** [zefoy/ngx-color-picker#90]
Hi, 

When settings [cpDisableInput] to true, arrows remain visible on the OK Button : 
![image](https://user-images.githubusercontent.com/29368953/34292853-bb57da44-e702-11e7-88ab-f867127b03f8.png)

Here's my markup : 
```
<input class="form-control input-sm" [(colorPicker)]="company.Colour" [style.background]="company.Colour" readonly="readonly"
                       [cpDisableInput]="true" [cpAlphaChannel]="'disabled'" [cpFallbackColor]="'#FFF'" [cpOKButton]="true" [cpOKButtonClass]="'btn btn-sm btn-block btn-primary'"/>
```

Btw, thank you for the awesome module !

**Comment by sconix** [comment]
Thanks, will fix and make a new release today.
