### ISSUE TITLE
Performance issue when instantiating multiple instances

### ISSUE THREAD

**Issue by zippos** [zefoy/ngx-color-picker#91]
Hello, I'm using this directive on a dynamic component which I create and then destroy multiple times, depending on what items I click in the DOM. I've notices a high load since I switched to this color picker and a lot of bottlenecks after a 10-20 instantiation. I've tried replicating this without the colorpicker, but it worked smooth (no bottlenecks). Is there any way I can bypass this issue? Thanks!

**Comment by sconix** [comment]
What do you mean by bottlenecks? Are you referring to a performance issue? If yes then is this issue about memory leak of performance? I am assuming that you are talking about performance issue if not then I would like to know how determine it to be memory leak).

We haven't noticed this in our app which also uses this in a dynamic component. But I just did a full code cleanup and while doing that I noticed possible issue with inline mode (and some rare situations with popup mode) where event listeners could stay on after destroy which could explain your issue. So maybe you could try the 5.3.0 which is out really soon (today most likely). And if you still experience the issue then could you be bit more specific (i.e. answer my first question). Even better would be if you can replicate the issue with the Plunker template.

**Comment by zippos** [comment]
Well, it's more like a performance issue and I'm not 100% sure it's caused by this color-picker, but I've been struggling for days to find the source of the issue and disabling the color picker seemed to fix it.

I've also found a bug in Angular which causes memory leaks on dynamically created components, and it really nasty. So this causes issues also, but they are less noticeable while the color-picker is disabled (https://github.com/angular/angular/issues/19997) 

I'll wait for the new version, maybe it will fix something.
Thanks for your fast response. I appreciate it.

**Comment by sconix** [comment]
The 5.3.0 is now out so please try it. If it still happens it would be good if you could try to replicate it with the Plunker example or at least share your config / colorpicker options that you use (preferable through Plunker example).
