### ISSUE TITLE
Add support for form controls

### ISSUE THREAD

**Issue by lworkman** [zefoy/ngx-color-picker#92]
Because this is used through an input, are we able to add support for `formControls`? I'd be happy to contribute, the code seems to already be there basically. I would think it would be an input like `[cpFormControl]`.

**Comment by sconix** [comment]
Sure PR would be more than welcome.

**Comment by prasad1791** [comment]
is there any progress on formcontrol ?

**Comment by lworkman** [comment]
No, sorry, I never ended up going down this path.
