### ISSUE TITLE
Changing input manually bugs out

### ISSUE THREAD

**Issue by misha130** [zefoy/ngx-color-picker#93]
```
        <input class="absolute transparent  color-picker-body"
           
            [colorPicker]="color" />
```

Clicking and changing the input from lets say #000 to #001 then closing the dialog shows error:

> colorString || "").toLowerCase is not a function
>     at ColorPickerService.stringToHsva
>

**Comment by sconix** [comment]
I am not able to reproduce this. Can you try to reproduce it with the Plunker template?
