### ISSUE TITLE
Multiple color pickers in one page?

### ISSUE THREAD

**Issue by rossmuego** [zefoy/ngx-color-picker#94]
Is it at all possible to have multiple color pickers in the one HTML document? Whenever I try this when I change the color of one, all of the color-pickers change to the color just selected.

**Comment by sconix** [comment]
Of course it is, they are not connected to each other unless you do so. Even the example app has multiple color pickers in one page.

**Comment by mafav** [comment]
I had this problem as well. Just assign each [(colorPicker]) a unique value
