### ISSUE TITLE
Hex code not shown

### ISSUE THREAD

**Issue by sakthivelsubbarayan** [zefoy/ngx-color-picker#96]
I'm using the following code to integrate the color picker.

  <input type="text" [(colorPicker)]="background_color" class="c-l-tab-input w-input" name="Stripe-Background-Colour" [(ngModel)]="background_color" data-name="Stripe Background Colour">

But i have a problem with hex code label.The label text color is not shown.Because the text color is white.
               
![screenshot](https://user-images.githubusercontent.com/30147172/35671196-a2905134-0760-11e8-861c-47c4386f1d18.png)

**Comment by sconix** [comment]
You need to fix your CSS style so that they don't modify the color picker styles.

**Comment by sakthivelsubbarayan** [comment]
Thanks for your quick response.I fixed that issue.
