### ISSUE TITLE
Error when add cpDialogDisplay = "'inline'"

### ISSUE THREAD

**Issue by EduhCosta** [zefoy/ngx-color-picker#98]
Help me please, 

I want to use the always-open picker in my application, but when I add the **[cpDialogDisplay] = "'inline'"** tag, both in the input and in a span, it returns an error and generates this error until I lock my PC.

Can anybody help me??

Code:
` <div> `
   ` <input [(colorPicker)]="color" `
        `   [style.background]="color"`
      `     [cpToggle]="true"`
    `       [cpDialogDisplay]="'inline'"`
  `         [cpPosition]="'bottom'" />`
`</div>`

Error:
![captura de tela 2018-02-05 as 14 07 28](https://user-images.githubusercontent.com/16820917/35818301-6ae0f934-0a7e-11e8-8f9c-0a25b9656f84.png)

**Comment by daniel-mueller-me** [comment]
We have the same problem here.

As a workaround, you can trigger click to open the picker manually.

`this.colorPickerRef.nativeElement.click();`

**Comment by sconix** [comment]
If somebody can make reproduction with the Plunker template that will speed up things by enabling me to have a quick look of the issue between my busy schedule :)
