### ISSUE TITLE
Angular 4 AOT webpack - ERROR in window is not defined

### ISSUE THREAD

**Issue by AlexanderLea** [zefoy/ngx-color-picker#99]
Hi,

I'm getting AOT build errors trying to implement a simple colour picker.

**package.json** 
`"ngx-color-picker": "4.5.3"`

**app.module**
```
@NgModule({
    imports: [ColorPickerModule]
....
```

component
`<input [(colorPicker)]="primaryColour" [style.background]="primaryColour" [cpPosition]="'top'" (cpToggleChange)="onColourPickerToggle($event)" `data-automation="136aff2"/>`
`

The error running my webpack production build - I get: _ERROR in window is not defined_, which disappears as soon as I remove the npm package and remove references.

I imagine I'm missing something obvious - your demos compile with AOT ok. 

Any idea/help/suggestions would be much appreciated!

Alex

**Comment by sconix** [comment]
I am closing this issue due to being so old, if this is still valid let me know. Although I have no idea what could cause that error unless you are trying to do SSR.
